package fileclassify

import (
	"reflect"
	"testing"
)

func TestClassifyPathRules(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		in   Input
		want Classification
	}{
		{
			name: "generated sqlc file under dbgen",
			in:   Input{Path: "services/cocoded/internal/db/dbgen/snapshots.sql.go"},
			want: Classification{
				Path:              "services/cocoded/internal/db/dbgen/snapshots.sql.go",
				Generated:         true,
				ExcludedCandidate: true,
				Reasons:           []Reason{ReasonGeneratedPath, ReasonGeneratedDirectory},
			},
		},
		{
			name: "explicit binary diff",
			in:   Input{Path: "assets/logo.svg", Binary: true},
			want: Classification{
				Path:              "assets/logo.svg",
				Binary:            true,
				ExcludedCandidate: true,
				Reasons:           []Reason{ReasonExplicitBinary},
			},
		},
		{
			name: "binary extension",
			in:   Input{Path: "web/public/avatar.PNG"},
			want: Classification{
				Path:              "web/public/avatar.PNG",
				Binary:            true,
				ExcludedCandidate: true,
				Reasons:           []Reason{ReasonBinaryExtension},
			},
		},
		{
			name: "lockfile",
			in:   Input{Path: "frontend/pnpm-lock.yaml"},
			want: Classification{
				Path:              "frontend/pnpm-lock.yaml",
				Lockfile:          true,
				ExcludedCandidate: true,
				Reasons:           []Reason{ReasonLockfile},
			},
		},
		{
			name: "vendor path",
			in:   Input{Path: "third_party/vendor/module/file.go"},
			want: Classification{
				Path:              "third_party/vendor/module/file.go",
				Vendor:            true,
				ExcludedCandidate: true,
				Reasons:           []Reason{ReasonVendorDirectory},
			},
		},
		{
			name: "dependency directory excluded candidate",
			in:   Input{Path: "web/node_modules/pkg/index.js"},
			want: Classification{
				Path:              "web/node_modules/pkg/index.js",
				ExcludedCandidate: true,
				Reasons:           []Reason{ReasonDependencyDirectory},
			},
		},
		{
			name: "build output directory excluded candidate",
			in:   Input{Path: "app/dist/main.js"},
			want: Classification{
				Path:              "app/dist/main.js",
				Generated:         true,
				ExcludedCandidate: true,
				Reasons:           []Reason{ReasonGeneratedPath, ReasonBuildOutputDirectory},
			},
		},
		{
			name: "ordinary source file",
			in:   Input{Path: "./services/cocoded/internal/diffparse/parser.go"},
			want: Classification{Path: "services/cocoded/internal/diffparse/parser.go"},
		},
		{
			name: "uses old path when path is empty",
			in:   Input{OldPath: "a/deleted/file.go"},
			want: Classification{Path: "a/deleted/file.go"},
		},
		{
			name: "normalizes windows separators",
			in:   Input{Path: `b\cmd\cocoded\main.go`},
			want: Classification{Path: "b/cmd/cocoded/main.go"},
		},
		{
			name: "vendor substring is not a vendor directory",
			in:   Input{Path: "cmd/vendorize/main.go"},
			want: Classification{Path: "cmd/vendorize/main.go"},
		},
		{
			name: "svg is text unless explicitly binary",
			in:   Input{Path: "assets/icon.svg"},
			want: Classification{Path: "assets/icon.svg"},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			got := Classify(tt.in)
			if !reflect.DeepEqual(got, tt.want) {
				t.Fatalf("Classify() = %+v, want %+v", got, tt.want)
			}
		})
	}
}

func TestClassifyContentRules(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		in   Input
		want Classification
	}{
		{
			name: "go generated header",
			in: Input{
				Path:          "internal/api/client.go",
				ContentPrefix: []byte("// Code generated by openapi-generator. DO NOT EDIT.\npackage api\n"),
			},
			want: Classification{
				Path:              "internal/api/client.go",
				Generated:         true,
				ExcludedCandidate: true,
				Reasons:           []Reason{ReasonGeneratedMarker},
			},
		},
		{
			name: "null byte marks binary",
			in: Input{
				Path:          "assets/data.dat",
				ContentPrefix: []byte{'a', 0, 'b'},
			},
			want: Classification{
				Path:              "assets/data.dat",
				Binary:            true,
				ExcludedCandidate: true,
				Reasons:           []Reason{ReasonBinaryContent},
			},
		},
		{
			name: "invalid utf8 marks binary",
			in: Input{
				Path:          "assets/data.txt",
				ContentPrefix: []byte{0xff, 0xfe, 0xfd},
			},
			want: Classification{
				Path:              "assets/data.txt",
				Binary:            true,
				ExcludedCandidate: true,
				Reasons:           []Reason{ReasonBinaryContent},
			},
		},
		{
			name: "marker beyond prefix scan limit is ignored",
			in: Input{
				Path:          "docs/notes.md",
				ContentPrefix: append(bytesOf('x', 8193), []byte("Code generated by docs tool")...),
			},
			want: Classification{Path: "docs/notes.md"},
		},
		{
			name: "empty content does not imply binary",
			in: Input{
				Path:          "README.md",
				ContentPrefix: nil,
			},
			want: Classification{Path: "README.md"},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			got := Classify(tt.in)
			if !reflect.DeepEqual(got, tt.want) {
				t.Fatalf("Classify() = %+v, want %+v", got, tt.want)
			}
		})
	}
}

func bytesOf(value byte, count int) []byte {
	out := make([]byte, count)
	for i := range out {
		out[i] = value
	}
	return out
}
