package fileclassify

import (
	"bytes"
	"path"
	"strings"
	"unicode/utf8"
)

type Input struct {
	Path    string
	OldPath string
	Binary  bool

	// ContentPrefix should contain the beginning of the file when available.
	// Classification stays path-only when it is empty.
	ContentPrefix []byte
}

type Classification struct {
	Path              string
	Generated         bool
	Binary            bool
	Lockfile          bool
	Vendor            bool
	ExcludedCandidate bool
	Reasons           []Reason
}

type Reason string

const (
	ReasonExplicitBinary       Reason = "explicit_binary"
	ReasonBinaryExtension      Reason = "binary_extension"
	ReasonBinaryContent        Reason = "binary_content"
	ReasonGeneratedPath        Reason = "generated_path"
	ReasonGeneratedMarker      Reason = "generated_marker"
	ReasonGeneratedDirectory   Reason = "generated_directory"
	ReasonLockfile             Reason = "lockfile"
	ReasonVendorDirectory      Reason = "vendor_directory"
	ReasonDependencyDirectory  Reason = "dependency_directory"
	ReasonBuildOutputDirectory Reason = "build_output_directory"
)

func Classify(input Input) Classification {
	p := normalizePath(input.Path)
	if p == "" {
		p = normalizePath(input.OldPath)
	}

	var out Classification
	out.Path = p

	lowerPath := strings.ToLower(p)
	base := path.Base(lowerPath)
	segments := splitPath(lowerPath)

	if input.Binary {
		out.Binary = true
		out.addReason(ReasonExplicitBinary)
	}
	if hasBinaryExtension(base) {
		out.Binary = true
		out.addReason(ReasonBinaryExtension)
	}
	if looksBinary(input.ContentPrefix) {
		out.Binary = true
		out.addReason(ReasonBinaryContent)
	}

	if hasGeneratedPath(lowerPath, base) {
		out.Generated = true
		out.addReason(ReasonGeneratedPath)
	}
	if hasGeneratedDirectory(segments) {
		out.Generated = true
		out.addReason(ReasonGeneratedDirectory)
	}
	if hasGeneratedMarker(input.ContentPrefix) {
		out.Generated = true
		out.addReason(ReasonGeneratedMarker)
	}

	if isLockfile(base) {
		out.Lockfile = true
		out.addReason(ReasonLockfile)
	}
	if hasVendorDirectory(segments) {
		out.Vendor = true
		out.addReason(ReasonVendorDirectory)
	}
	if hasDependencyDirectory(segments) {
		out.ExcludedCandidate = true
		out.addReason(ReasonDependencyDirectory)
	}
	if hasBuildOutputDirectory(segments) {
		out.ExcludedCandidate = true
		out.addReason(ReasonBuildOutputDirectory)
	}

	if out.Generated || out.Binary || out.Lockfile || out.Vendor {
		out.ExcludedCandidate = true
	}

	return out
}

func (c *Classification) addReason(reason Reason) {
	for _, existing := range c.Reasons {
		if existing == reason {
			return
		}
	}
	c.Reasons = append(c.Reasons, reason)
}

func normalizePath(p string) string {
	p = strings.TrimSpace(p)
	p = strings.ReplaceAll(p, `\`, "/")
	p = strings.TrimPrefix(p, "./")
	if p == "" {
		return ""
	}
	return path.Clean(p)
}

func splitPath(p string) []string {
	if p == "." || p == "" {
		return nil
	}
	return strings.Split(p, "/")
}

func hasBinaryExtension(base string) bool {
	switch path.Ext(base) {
	case ".7z", ".a", ".avif", ".bin", ".bmp", ".bz2", ".class", ".dll", ".dmg",
		".eot", ".exe", ".gif", ".gz", ".ico", ".jar", ".jpeg", ".jpg", ".mov",
		".mp3", ".mp4", ".o", ".otf", ".pdf", ".png", ".so", ".tar", ".tgz",
		".ttf", ".webm", ".webp", ".woff", ".woff2", ".zip":
		return true
	default:
		return false
	}
}

func looksBinary(content []byte) bool {
	if len(content) == 0 {
		return false
	}
	if bytes.IndexByte(content, 0) >= 0 {
		return true
	}
	return !utf8.Valid(content)
}

func hasGeneratedPath(p string, base string) bool {
	generatedSuffixes := []string{
		".pb.go",
		".pb.gw.go",
		".gen.go",
		".generated.go",
		"_generated.go",
		".sql.go",
		".designer.cs",
		".g.dart",
		".freezed.dart",
	}
	for _, suffix := range generatedSuffixes {
		if strings.HasSuffix(base, suffix) {
			return true
		}
	}

	generatedNames := map[string]struct{}{
		"bundle.js":    {},
		"bundle.css":   {},
		"schema.pb.go": {},
		"swagger.json": {},
		"openapi.json": {},
		"openapi.yaml": {},
		"openapi.yml":  {},
	}
	if _, ok := generatedNames[base]; ok {
		return true
	}

	return strings.Contains(p, "/dist/") && (strings.HasSuffix(base, ".js") || strings.HasSuffix(base, ".css"))
}

func hasGeneratedDirectory(segments []string) bool {
	for _, segment := range segments {
		switch segment {
		case "dbgen", "generated", "gen":
			return true
		}
	}
	return false
}

func hasGeneratedMarker(content []byte) bool {
	if len(content) == 0 {
		return false
	}
	if len(content) > 8192 {
		content = content[:8192]
	}
	lower := strings.ToLower(string(content))
	markers := []string{
		"code generated",
		"do not edit",
		"auto-generated",
		"autogenerated",
		"@generated",
		"this file was generated",
		"generated by",
	}
	for _, marker := range markers {
		if strings.Contains(lower, marker) {
			return true
		}
	}
	return false
}

func isLockfile(base string) bool {
	switch base {
	case "bun.lock", "cargo.lock", "composer.lock", "go.sum", "package-lock.json",
		"pnpm-lock.yaml", "poetry.lock", "yarn.lock":
		return true
	default:
		return strings.HasSuffix(base, ".lock")
	}
}

func hasVendorDirectory(segments []string) bool {
	for _, segment := range segments {
		if segment == "vendor" {
			return true
		}
	}
	return false
}

func hasDependencyDirectory(segments []string) bool {
	for _, segment := range segments {
		switch segment {
		case "node_modules", "bower_components":
			return true
		}
	}
	return false
}

func hasBuildOutputDirectory(segments []string) bool {
	for _, segment := range segments {
		switch segment {
		case ".next", ".nuxt", "build", "coverage", "dist", "target":
			return true
		}
	}
	return false
}
