// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createAgentConfig = `-- name: CreateAgentConfig :one
INSERT INTO agent_configs (
  id,
  name,
  role,
  adapter_kind,
  command,
  args_json,
  cwd_mode,
  env_allowlist_json,
  output_mode,
  model_label,
  reasoning_label,
  capabilities_json,
  settings_json,
  enabled,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, name, role, adapter_kind, command, args_json, cwd_mode, env_allowlist_json, output_mode, model_label, reasoning_label, capabilities_json, settings_json, enabled, created_at, updated_at
`

type CreateAgentConfigParams struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Role             string         `json:"role"`
	AdapterKind      string         `json:"adapter_kind"`
	Command          sql.NullString `json:"command"`
	ArgsJson         string         `json:"args_json"`
	CwdMode          string         `json:"cwd_mode"`
	EnvAllowlistJson string         `json:"env_allowlist_json"`
	OutputMode       string         `json:"output_mode"`
	ModelLabel       sql.NullString `json:"model_label"`
	ReasoningLabel   sql.NullString `json:"reasoning_label"`
	CapabilitiesJson string         `json:"capabilities_json"`
	SettingsJson     string         `json:"settings_json"`
	Enabled          int64          `json:"enabled"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) CreateAgentConfig(ctx context.Context, arg CreateAgentConfigParams) (AgentConfig, error) {
	row := q.db.QueryRowContext(ctx, createAgentConfig,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.AdapterKind,
		arg.Command,
		arg.ArgsJson,
		arg.CwdMode,
		arg.EnvAllowlistJson,
		arg.OutputMode,
		arg.ModelLabel,
		arg.ReasoningLabel,
		arg.CapabilitiesJson,
		arg.SettingsJson,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AgentConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.AdapterKind,
		&i.Command,
		&i.ArgsJson,
		&i.CwdMode,
		&i.EnvAllowlistJson,
		&i.OutputMode,
		&i.ModelLabel,
		&i.ReasoningLabel,
		&i.CapabilitiesJson,
		&i.SettingsJson,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentRun = `-- name: CreateAgentRun :one
INSERT INTO agent_runs (
  id,
  review_session_id,
  agent_config_id,
  context_bundle_id,
  status,
  role,
  started_at,
  completed_at,
  duration_ms,
  exit_code,
  stdout_artifact_id,
  stderr_artifact_id,
  parsed_output_artifact_id,
  error_code,
  error_message,
  metadata_json
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, review_session_id, agent_config_id, context_bundle_id, status, role, started_at, completed_at, duration_ms, exit_code, stdout_artifact_id, stderr_artifact_id, parsed_output_artifact_id, error_code, error_message, metadata_json
`

type CreateAgentRunParams struct {
	ID                     string         `json:"id"`
	ReviewSessionID        string         `json:"review_session_id"`
	AgentConfigID          string         `json:"agent_config_id"`
	ContextBundleID        sql.NullString `json:"context_bundle_id"`
	Status                 string         `json:"status"`
	Role                   string         `json:"role"`
	StartedAt              sql.NullString `json:"started_at"`
	CompletedAt            sql.NullString `json:"completed_at"`
	DurationMs             sql.NullInt64  `json:"duration_ms"`
	ExitCode               sql.NullInt64  `json:"exit_code"`
	StdoutArtifactID       sql.NullString `json:"stdout_artifact_id"`
	StderrArtifactID       sql.NullString `json:"stderr_artifact_id"`
	ParsedOutputArtifactID sql.NullString `json:"parsed_output_artifact_id"`
	ErrorCode              sql.NullString `json:"error_code"`
	ErrorMessage           sql.NullString `json:"error_message"`
	MetadataJson           string         `json:"metadata_json"`
}

func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, createAgentRun,
		arg.ID,
		arg.ReviewSessionID,
		arg.AgentConfigID,
		arg.ContextBundleID,
		arg.Status,
		arg.Role,
		arg.StartedAt,
		arg.CompletedAt,
		arg.DurationMs,
		arg.ExitCode,
		arg.StdoutArtifactID,
		arg.StderrArtifactID,
		arg.ParsedOutputArtifactID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.MetadataJson,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentConfigID,
		&i.ContextBundleID,
		&i.Status,
		&i.Role,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.ExitCode,
		&i.StdoutArtifactID,
		&i.StderrArtifactID,
		&i.ParsedOutputArtifactID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.MetadataJson,
	)
	return i, err
}

const createReviewSessionAgent = `-- name: CreateReviewSessionAgent :one
INSERT INTO review_session_agents (
  id,
  review_session_id,
  agent_config_id,
  role,
  run_order,
  enabled,
  settings_override_json
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, review_session_id, agent_config_id, role, run_order, enabled, settings_override_json
`

type CreateReviewSessionAgentParams struct {
	ID                   string `json:"id"`
	ReviewSessionID      string `json:"review_session_id"`
	AgentConfigID        string `json:"agent_config_id"`
	Role                 string `json:"role"`
	RunOrder             int64  `json:"run_order"`
	Enabled              int64  `json:"enabled"`
	SettingsOverrideJson string `json:"settings_override_json"`
}

func (q *Queries) CreateReviewSessionAgent(ctx context.Context, arg CreateReviewSessionAgentParams) (ReviewSessionAgent, error) {
	row := q.db.QueryRowContext(ctx, createReviewSessionAgent,
		arg.ID,
		arg.ReviewSessionID,
		arg.AgentConfigID,
		arg.Role,
		arg.RunOrder,
		arg.Enabled,
		arg.SettingsOverrideJson,
	)
	var i ReviewSessionAgent
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentConfigID,
		&i.Role,
		&i.RunOrder,
		&i.Enabled,
		&i.SettingsOverrideJson,
	)
	return i, err
}

const deleteAgentConfig = `-- name: DeleteAgentConfig :exec
DELETE FROM agent_configs
WHERE id = ?
`

func (q *Queries) DeleteAgentConfig(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentConfig, id)
	return err
}

const getAgentConfig = `-- name: GetAgentConfig :one
SELECT id, name, role, adapter_kind, command, args_json, cwd_mode, env_allowlist_json, output_mode, model_label, reasoning_label, capabilities_json, settings_json, enabled, created_at, updated_at
FROM agent_configs
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAgentConfig(ctx context.Context, id string) (AgentConfig, error) {
	row := q.db.QueryRowContext(ctx, getAgentConfig, id)
	var i AgentConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.AdapterKind,
		&i.Command,
		&i.ArgsJson,
		&i.CwdMode,
		&i.EnvAllowlistJson,
		&i.OutputMode,
		&i.ModelLabel,
		&i.ReasoningLabel,
		&i.CapabilitiesJson,
		&i.SettingsJson,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentRun = `-- name: GetAgentRun :one
SELECT id, review_session_id, agent_config_id, context_bundle_id, status, role, started_at, completed_at, duration_ms, exit_code, stdout_artifact_id, stderr_artifact_id, parsed_output_artifact_id, error_code, error_message, metadata_json
FROM agent_runs
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAgentRun(ctx context.Context, id string) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, getAgentRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentConfigID,
		&i.ContextBundleID,
		&i.Status,
		&i.Role,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.ExitCode,
		&i.StdoutArtifactID,
		&i.StderrArtifactID,
		&i.ParsedOutputArtifactID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.MetadataJson,
	)
	return i, err
}

const listAgentConfigs = `-- name: ListAgentConfigs :many
SELECT id, name, role, adapter_kind, command, args_json, cwd_mode, env_allowlist_json, output_mode, model_label, reasoning_label, capabilities_json, settings_json, enabled, created_at, updated_at
FROM agent_configs
ORDER BY enabled DESC, name ASC
`

func (q *Queries) ListAgentConfigs(ctx context.Context) ([]AgentConfig, error) {
	rows, err := q.db.QueryContext(ctx, listAgentConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConfig{}
	for rows.Next() {
		var i AgentConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.AdapterKind,
			&i.Command,
			&i.ArgsJson,
			&i.CwdMode,
			&i.EnvAllowlistJson,
			&i.OutputMode,
			&i.ModelLabel,
			&i.ReasoningLabel,
			&i.CapabilitiesJson,
			&i.SettingsJson,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRunsBySession = `-- name: ListAgentRunsBySession :many
SELECT id, review_session_id, agent_config_id, context_bundle_id, status, role, started_at, completed_at, duration_ms, exit_code, stdout_artifact_id, stderr_artifact_id, parsed_output_artifact_id, error_code, error_message, metadata_json
FROM agent_runs
WHERE review_session_id = ?
ORDER BY started_at ASC, id ASC
`

func (q *Queries) ListAgentRunsBySession(ctx context.Context, reviewSessionID string) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRunsBySession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.ReviewSessionID,
			&i.AgentConfigID,
			&i.ContextBundleID,
			&i.Status,
			&i.Role,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.ExitCode,
			&i.StdoutArtifactID,
			&i.StderrArtifactID,
			&i.ParsedOutputArtifactID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewSessionAgents = `-- name: ListReviewSessionAgents :many
SELECT id, review_session_id, agent_config_id, role, run_order, enabled, settings_override_json
FROM review_session_agents
WHERE review_session_id = ?
ORDER BY run_order ASC, role ASC
`

func (q *Queries) ListReviewSessionAgents(ctx context.Context, reviewSessionID string) ([]ReviewSessionAgent, error) {
	rows, err := q.db.QueryContext(ctx, listReviewSessionAgents, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewSessionAgent{}
	for rows.Next() {
		var i ReviewSessionAgent
		if err := rows.Scan(
			&i.ID,
			&i.ReviewSessionID,
			&i.AgentConfigID,
			&i.Role,
			&i.RunOrder,
			&i.Enabled,
			&i.SettingsOverrideJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentConfig = `-- name: UpdateAgentConfig :one
UPDATE agent_configs
SET
  name = ?,
  role = ?,
  command = ?,
  args_json = ?,
  cwd_mode = ?,
  env_allowlist_json = ?,
  output_mode = ?,
  model_label = ?,
  reasoning_label = ?,
  capabilities_json = ?,
  settings_json = ?,
  enabled = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, name, role, adapter_kind, command, args_json, cwd_mode, env_allowlist_json, output_mode, model_label, reasoning_label, capabilities_json, settings_json, enabled, created_at, updated_at
`

type UpdateAgentConfigParams struct {
	Name             string         `json:"name"`
	Role             string         `json:"role"`
	Command          sql.NullString `json:"command"`
	ArgsJson         string         `json:"args_json"`
	CwdMode          string         `json:"cwd_mode"`
	EnvAllowlistJson string         `json:"env_allowlist_json"`
	OutputMode       string         `json:"output_mode"`
	ModelLabel       sql.NullString `json:"model_label"`
	ReasoningLabel   sql.NullString `json:"reasoning_label"`
	CapabilitiesJson string         `json:"capabilities_json"`
	SettingsJson     string         `json:"settings_json"`
	Enabled          int64          `json:"enabled"`
	UpdatedAt        string         `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateAgentConfig(ctx context.Context, arg UpdateAgentConfigParams) (AgentConfig, error) {
	row := q.db.QueryRowContext(ctx, updateAgentConfig,
		arg.Name,
		arg.Role,
		arg.Command,
		arg.ArgsJson,
		arg.CwdMode,
		arg.EnvAllowlistJson,
		arg.OutputMode,
		arg.ModelLabel,
		arg.ReasoningLabel,
		arg.CapabilitiesJson,
		arg.SettingsJson,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i AgentConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.AdapterKind,
		&i.Command,
		&i.ArgsJson,
		&i.CwdMode,
		&i.EnvAllowlistJson,
		&i.OutputMode,
		&i.ModelLabel,
		&i.ReasoningLabel,
		&i.CapabilitiesJson,
		&i.SettingsJson,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentRunStatus = `-- name: UpdateAgentRunStatus :one
UPDATE agent_runs
SET
  status = ?,
  started_at = ?,
  completed_at = ?,
  duration_ms = ?,
  exit_code = ?,
  stdout_artifact_id = ?,
  stderr_artifact_id = ?,
  parsed_output_artifact_id = ?,
  error_code = ?,
  error_message = ?,
  metadata_json = ?
WHERE id = ?
RETURNING id, review_session_id, agent_config_id, context_bundle_id, status, role, started_at, completed_at, duration_ms, exit_code, stdout_artifact_id, stderr_artifact_id, parsed_output_artifact_id, error_code, error_message, metadata_json
`

type UpdateAgentRunStatusParams struct {
	Status                 string         `json:"status"`
	StartedAt              sql.NullString `json:"started_at"`
	CompletedAt            sql.NullString `json:"completed_at"`
	DurationMs             sql.NullInt64  `json:"duration_ms"`
	ExitCode               sql.NullInt64  `json:"exit_code"`
	StdoutArtifactID       sql.NullString `json:"stdout_artifact_id"`
	StderrArtifactID       sql.NullString `json:"stderr_artifact_id"`
	ParsedOutputArtifactID sql.NullString `json:"parsed_output_artifact_id"`
	ErrorCode              sql.NullString `json:"error_code"`
	ErrorMessage           sql.NullString `json:"error_message"`
	MetadataJson           string         `json:"metadata_json"`
	ID                     string         `json:"id"`
}

func (q *Queries) UpdateAgentRunStatus(ctx context.Context, arg UpdateAgentRunStatusParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, updateAgentRunStatus,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.DurationMs,
		arg.ExitCode,
		arg.StdoutArtifactID,
		arg.StderrArtifactID,
		arg.ParsedOutputArtifactID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.MetadataJson,
		arg.ID,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentConfigID,
		&i.ContextBundleID,
		&i.Status,
		&i.Role,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.ExitCode,
		&i.StdoutArtifactID,
		&i.StderrArtifactID,
		&i.ParsedOutputArtifactID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.MetadataJson,
	)
	return i, err
}

const updateReviewSessionAgentEnabled = `-- name: UpdateReviewSessionAgentEnabled :one
UPDATE review_session_agents
SET enabled = ?
WHERE id = ?
RETURNING id, review_session_id, agent_config_id, role, run_order, enabled, settings_override_json
`

type UpdateReviewSessionAgentEnabledParams struct {
	Enabled int64  `json:"enabled"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateReviewSessionAgentEnabled(ctx context.Context, arg UpdateReviewSessionAgentEnabledParams) (ReviewSessionAgent, error) {
	row := q.db.QueryRowContext(ctx, updateReviewSessionAgentEnabled, arg.Enabled, arg.ID)
	var i ReviewSessionAgent
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentConfigID,
		&i.Role,
		&i.RunOrder,
		&i.Enabled,
		&i.SettingsOverrideJson,
	)
	return i, err
}
