// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (
  id,
  workspace_id,
  review_session_id,
  kind,
  relative_path,
  content_type,
  size_bytes,
  sha256,
  metadata_json,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, workspace_id, review_session_id, kind, relative_path, content_type, size_bytes, sha256, metadata_json, created_at
`

type CreateArtifactParams struct {
	ID              string         `json:"id"`
	WorkspaceID     string         `json:"workspace_id"`
	ReviewSessionID sql.NullString `json:"review_session_id"`
	Kind            string         `json:"kind"`
	RelativePath    string         `json:"relative_path"`
	ContentType     string         `json:"content_type"`
	SizeBytes       int64          `json:"size_bytes"`
	Sha256          sql.NullString `json:"sha256"`
	MetadataJson    string         `json:"metadata_json"`
	CreatedAt       string         `json:"created_at"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, createArtifact,
		arg.ID,
		arg.WorkspaceID,
		arg.ReviewSessionID,
		arg.Kind,
		arg.RelativePath,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReviewSessionID,
		&i.Kind,
		&i.RelativePath,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifacts
WHERE id = ?
`

func (q *Queries) DeleteArtifact(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteArtifact, id)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, workspace_id, review_session_id, kind, relative_path, content_type, size_bytes, sha256, metadata_json, created_at
FROM artifacts
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReviewSessionID,
		&i.Kind,
		&i.RelativePath,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsByReviewSession = `-- name: ListArtifactsByReviewSession :many
SELECT id, workspace_id, review_session_id, kind, relative_path, content_type, size_bytes, sha256, metadata_json, created_at
FROM artifacts
WHERE review_session_id = ?
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListArtifactsByReviewSession(ctx context.Context, reviewSessionID sql.NullString) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByReviewSession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ReviewSessionID,
			&i.Kind,
			&i.RelativePath,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByWorkspace = `-- name: ListArtifactsByWorkspace :many
SELECT id, workspace_id, review_session_id, kind, relative_path, content_type, size_bytes, sha256, metadata_json, created_at
FROM artifacts
WHERE workspace_id = ?
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListArtifactsByWorkspace(ctx context.Context, workspaceID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ReviewSessionID,
			&i.Kind,
			&i.RelativePath,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
