// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context_bundles.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createContextBundle = `-- name: CreateContextBundle :one
INSERT INTO context_bundles (
  id,
  review_session_id,
  agent_config_id,
  scope,
  token_estimate,
  item_count,
  artifact_id,
  policy_json,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, review_session_id, agent_config_id, scope, token_estimate, item_count, artifact_id, policy_json, created_at
`

type CreateContextBundleParams struct {
	ID              string         `json:"id"`
	ReviewSessionID string         `json:"review_session_id"`
	AgentConfigID   sql.NullString `json:"agent_config_id"`
	Scope           string         `json:"scope"`
	TokenEstimate   int64          `json:"token_estimate"`
	ItemCount       int64          `json:"item_count"`
	ArtifactID      sql.NullString `json:"artifact_id"`
	PolicyJson      string         `json:"policy_json"`
	CreatedAt       string         `json:"created_at"`
}

func (q *Queries) CreateContextBundle(ctx context.Context, arg CreateContextBundleParams) (ContextBundle, error) {
	row := q.db.QueryRowContext(ctx, createContextBundle,
		arg.ID,
		arg.ReviewSessionID,
		arg.AgentConfigID,
		arg.Scope,
		arg.TokenEstimate,
		arg.ItemCount,
		arg.ArtifactID,
		arg.PolicyJson,
		arg.CreatedAt,
	)
	var i ContextBundle
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentConfigID,
		&i.Scope,
		&i.TokenEstimate,
		&i.ItemCount,
		&i.ArtifactID,
		&i.PolicyJson,
		&i.CreatedAt,
	)
	return i, err
}

const createContextItem = `-- name: CreateContextItem :one
INSERT INTO context_items (
  id,
  context_bundle_id,
  kind,
  path,
  start_line,
  end_line,
  title,
  content_artifact_id,
  token_estimate,
  metadata_json
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, context_bundle_id, kind, path, start_line, end_line, title, content_artifact_id, token_estimate, metadata_json
`

type CreateContextItemParams struct {
	ID                string         `json:"id"`
	ContextBundleID   string         `json:"context_bundle_id"`
	Kind              string         `json:"kind"`
	Path              sql.NullString `json:"path"`
	StartLine         sql.NullInt64  `json:"start_line"`
	EndLine           sql.NullInt64  `json:"end_line"`
	Title             sql.NullString `json:"title"`
	ContentArtifactID sql.NullString `json:"content_artifact_id"`
	TokenEstimate     int64          `json:"token_estimate"`
	MetadataJson      string         `json:"metadata_json"`
}

func (q *Queries) CreateContextItem(ctx context.Context, arg CreateContextItemParams) (ContextItem, error) {
	row := q.db.QueryRowContext(ctx, createContextItem,
		arg.ID,
		arg.ContextBundleID,
		arg.Kind,
		arg.Path,
		arg.StartLine,
		arg.EndLine,
		arg.Title,
		arg.ContentArtifactID,
		arg.TokenEstimate,
		arg.MetadataJson,
	)
	var i ContextItem
	err := row.Scan(
		&i.ID,
		&i.ContextBundleID,
		&i.Kind,
		&i.Path,
		&i.StartLine,
		&i.EndLine,
		&i.Title,
		&i.ContentArtifactID,
		&i.TokenEstimate,
		&i.MetadataJson,
	)
	return i, err
}

const deleteContextBundle = `-- name: DeleteContextBundle :exec
DELETE FROM context_bundles
WHERE id = ?
`

func (q *Queries) DeleteContextBundle(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteContextBundle, id)
	return err
}

const deleteContextItem = `-- name: DeleteContextItem :exec
DELETE FROM context_items
WHERE id = ?
`

func (q *Queries) DeleteContextItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteContextItem, id)
	return err
}

const getContextBundle = `-- name: GetContextBundle :one
SELECT id, review_session_id, agent_config_id, scope, token_estimate, item_count, artifact_id, policy_json, created_at
FROM context_bundles
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetContextBundle(ctx context.Context, id string) (ContextBundle, error) {
	row := q.db.QueryRowContext(ctx, getContextBundle, id)
	var i ContextBundle
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentConfigID,
		&i.Scope,
		&i.TokenEstimate,
		&i.ItemCount,
		&i.ArtifactID,
		&i.PolicyJson,
		&i.CreatedAt,
	)
	return i, err
}

const getContextItem = `-- name: GetContextItem :one
SELECT id, context_bundle_id, kind, path, start_line, end_line, title, content_artifact_id, token_estimate, metadata_json
FROM context_items
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetContextItem(ctx context.Context, id string) (ContextItem, error) {
	row := q.db.QueryRowContext(ctx, getContextItem, id)
	var i ContextItem
	err := row.Scan(
		&i.ID,
		&i.ContextBundleID,
		&i.Kind,
		&i.Path,
		&i.StartLine,
		&i.EndLine,
		&i.Title,
		&i.ContentArtifactID,
		&i.TokenEstimate,
		&i.MetadataJson,
	)
	return i, err
}

const listContextBundlesBySession = `-- name: ListContextBundlesBySession :many
SELECT id, review_session_id, agent_config_id, scope, token_estimate, item_count, artifact_id, policy_json, created_at
FROM context_bundles
WHERE review_session_id = ?
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListContextBundlesBySession(ctx context.Context, reviewSessionID string) ([]ContextBundle, error) {
	rows, err := q.db.QueryContext(ctx, listContextBundlesBySession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextBundle{}
	for rows.Next() {
		var i ContextBundle
		if err := rows.Scan(
			&i.ID,
			&i.ReviewSessionID,
			&i.AgentConfigID,
			&i.Scope,
			&i.TokenEstimate,
			&i.ItemCount,
			&i.ArtifactID,
			&i.PolicyJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContextItemsByBundle = `-- name: ListContextItemsByBundle :many
SELECT id, context_bundle_id, kind, path, start_line, end_line, title, content_artifact_id, token_estimate, metadata_json
FROM context_items
WHERE context_bundle_id = ?
ORDER BY id ASC
`

func (q *Queries) ListContextItemsByBundle(ctx context.Context, contextBundleID string) ([]ContextItem, error) {
	rows, err := q.db.QueryContext(ctx, listContextItemsByBundle, contextBundleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextItem{}
	for rows.Next() {
		var i ContextItem
		if err := rows.Scan(
			&i.ID,
			&i.ContextBundleID,
			&i.Kind,
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.Title,
			&i.ContentArtifactID,
			&i.TokenEstimate,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContextBundleArtifact = `-- name: UpdateContextBundleArtifact :one
UPDATE context_bundles
SET
  artifact_id = ?,
  token_estimate = ?,
  item_count = ?
WHERE id = ?
RETURNING id, review_session_id, agent_config_id, scope, token_estimate, item_count, artifact_id, policy_json, created_at
`

type UpdateContextBundleArtifactParams struct {
	ArtifactID    sql.NullString `json:"artifact_id"`
	TokenEstimate int64          `json:"token_estimate"`
	ItemCount     int64          `json:"item_count"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateContextBundleArtifact(ctx context.Context, arg UpdateContextBundleArtifactParams) (ContextBundle, error) {
	row := q.db.QueryRowContext(ctx, updateContextBundleArtifact,
		arg.ArtifactID,
		arg.TokenEstimate,
		arg.ItemCount,
		arg.ID,
	)
	var i ContextBundle
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentConfigID,
		&i.Scope,
		&i.TokenEstimate,
		&i.ItemCount,
		&i.ArtifactID,
		&i.PolicyJson,
		&i.CreatedAt,
	)
	return i, err
}
