// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copy_packets.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createCopyPacket = `-- name: CreateCopyPacket :one
INSERT INTO copy_packets (
  id,
  review_session_id,
  finding_id,
  format,
  content_artifact_id,
  finding_count,
  token_estimate,
  copied_at,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, review_session_id, finding_id, format, content_artifact_id, finding_count, token_estimate, copied_at, created_at
`

type CreateCopyPacketParams struct {
	ID                string         `json:"id"`
	ReviewSessionID   string         `json:"review_session_id"`
	FindingID         sql.NullString `json:"finding_id"`
	Format            string         `json:"format"`
	ContentArtifactID string         `json:"content_artifact_id"`
	FindingCount      int64          `json:"finding_count"`
	TokenEstimate     int64          `json:"token_estimate"`
	CopiedAt          sql.NullString `json:"copied_at"`
	CreatedAt         string         `json:"created_at"`
}

func (q *Queries) CreateCopyPacket(ctx context.Context, arg CreateCopyPacketParams) (CopyPacket, error) {
	row := q.db.QueryRowContext(ctx, createCopyPacket,
		arg.ID,
		arg.ReviewSessionID,
		arg.FindingID,
		arg.Format,
		arg.ContentArtifactID,
		arg.FindingCount,
		arg.TokenEstimate,
		arg.CopiedAt,
		arg.CreatedAt,
	)
	var i CopyPacket
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.FindingID,
		&i.Format,
		&i.ContentArtifactID,
		&i.FindingCount,
		&i.TokenEstimate,
		&i.CopiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCopyPacket = `-- name: GetCopyPacket :one
SELECT id, review_session_id, finding_id, format, content_artifact_id, finding_count, token_estimate, copied_at, created_at
FROM copy_packets
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetCopyPacket(ctx context.Context, id string) (CopyPacket, error) {
	row := q.db.QueryRowContext(ctx, getCopyPacket, id)
	var i CopyPacket
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.FindingID,
		&i.Format,
		&i.ContentArtifactID,
		&i.FindingCount,
		&i.TokenEstimate,
		&i.CopiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCopyPacketsBySession = `-- name: ListCopyPacketsBySession :many
SELECT id, review_session_id, finding_id, format, content_artifact_id, finding_count, token_estimate, copied_at, created_at
FROM copy_packets
WHERE review_session_id = ?
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListCopyPacketsBySession(ctx context.Context, reviewSessionID string) ([]CopyPacket, error) {
	rows, err := q.db.QueryContext(ctx, listCopyPacketsBySession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CopyPacket{}
	for rows.Next() {
		var i CopyPacket
		if err := rows.Scan(
			&i.ID,
			&i.ReviewSessionID,
			&i.FindingID,
			&i.Format,
			&i.ContentArtifactID,
			&i.FindingCount,
			&i.TokenEstimate,
			&i.CopiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCopyPacketCopied = `-- name: MarkCopyPacketCopied :one
UPDATE copy_packets
SET copied_at = ?
WHERE id = ?
RETURNING id, review_session_id, finding_id, format, content_artifact_id, finding_count, token_estimate, copied_at, created_at
`

type MarkCopyPacketCopiedParams struct {
	CopiedAt sql.NullString `json:"copied_at"`
	ID       string         `json:"id"`
}

func (q *Queries) MarkCopyPacketCopied(ctx context.Context, arg MarkCopyPacketCopiedParams) (CopyPacket, error) {
	row := q.db.QueryRowContext(ctx, markCopyPacketCopied, arg.CopiedAt, arg.ID)
	var i CopyPacket
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.FindingID,
		&i.Format,
		&i.ContentArtifactID,
		&i.FindingCount,
		&i.TokenEstimate,
		&i.CopiedAt,
		&i.CreatedAt,
	)
	return i, err
}
