// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package dbgen

import (
	"context"
)

const deleteCredentialRef = `-- name: DeleteCredentialRef :exec
DELETE FROM credential_refs
WHERE id = ?
`

func (q *Queries) DeleteCredentialRef(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCredentialRef, id)
	return err
}

const getCredentialRef = `-- name: GetCredentialRef :one
SELECT id, kind, display_name, storage_provider, storage_key, metadata_json, created_at, updated_at
FROM credential_refs
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetCredentialRef(ctx context.Context, id string) (CredentialRef, error) {
	row := q.db.QueryRowContext(ctx, getCredentialRef, id)
	var i CredentialRef
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.StorageProvider,
		&i.StorageKey,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestCredentialRefByKind = `-- name: GetLatestCredentialRefByKind :one
SELECT id, kind, display_name, storage_provider, storage_key, metadata_json, created_at, updated_at
FROM credential_refs
WHERE kind = ?
ORDER BY updated_at DESC, display_name ASC
LIMIT 1
`

func (q *Queries) GetLatestCredentialRefByKind(ctx context.Context, kind string) (CredentialRef, error) {
	row := q.db.QueryRowContext(ctx, getLatestCredentialRefByKind, kind)
	var i CredentialRef
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.StorageProvider,
		&i.StorageKey,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCredentialRef = `-- name: UpsertCredentialRef :one
INSERT INTO credential_refs (
  id,
  kind,
  display_name,
  storage_provider,
  storage_key,
  metadata_json,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON CONFLICT(id) DO UPDATE SET
  kind = excluded.kind,
  display_name = excluded.display_name,
  storage_provider = excluded.storage_provider,
  storage_key = excluded.storage_key,
  metadata_json = excluded.metadata_json,
  updated_at = excluded.updated_at
RETURNING id, kind, display_name, storage_provider, storage_key, metadata_json, created_at, updated_at
`

type UpsertCredentialRefParams struct {
	ID              string `json:"id"`
	Kind            string `json:"kind"`
	DisplayName     string `json:"display_name"`
	StorageProvider string `json:"storage_provider"`
	StorageKey      string `json:"storage_key"`
	MetadataJson    string `json:"metadata_json"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) UpsertCredentialRef(ctx context.Context, arg UpsertCredentialRefParams) (CredentialRef, error) {
	row := q.db.QueryRowContext(ctx, upsertCredentialRef,
		arg.ID,
		arg.Kind,
		arg.DisplayName,
		arg.StorageProvider,
		arg.StorageKey,
		arg.MetadataJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CredentialRef
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.StorageProvider,
		&i.StorageKey,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
