// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
  id,
  review_session_id,
  agent_run_id,
  type,
  level,
  sequence,
  payload_json,
  artifact_id,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, review_session_id, agent_run_id, type, level, sequence, payload_json, artifact_id, created_at
`

type CreateEventParams struct {
	ID              string         `json:"id"`
	ReviewSessionID sql.NullString `json:"review_session_id"`
	AgentRunID      sql.NullString `json:"agent_run_id"`
	Type            string         `json:"type"`
	Level           string         `json:"level"`
	Sequence        int64          `json:"sequence"`
	PayloadJson     string         `json:"payload_json"`
	ArtifactID      sql.NullString `json:"artifact_id"`
	CreatedAt       string         `json:"created_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.ID,
		arg.ReviewSessionID,
		arg.AgentRunID,
		arg.Type,
		arg.Level,
		arg.Sequence,
		arg.PayloadJson,
		arg.ArtifactID,
		arg.CreatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentRunID,
		&i.Type,
		&i.Level,
		&i.Sequence,
		&i.PayloadJson,
		&i.ArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, review_session_id, agent_run_id, type, level, sequence, payload_json, artifact_id, created_at
FROM events
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentRunID,
		&i.Type,
		&i.Level,
		&i.Sequence,
		&i.PayloadJson,
		&i.ArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsByReviewSession = `-- name: ListEventsByReviewSession :many
SELECT id, review_session_id, agent_run_id, type, level, sequence, payload_json, artifact_id, created_at
FROM events
WHERE review_session_id = ?
ORDER BY sequence ASC
`

func (q *Queries) ListEventsByReviewSession(ctx context.Context, reviewSessionID sql.NullString) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByReviewSession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ReviewSessionID,
			&i.AgentRunID,
			&i.Type,
			&i.Level,
			&i.Sequence,
			&i.PayloadJson,
			&i.ArtifactID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextEventSequence = `-- name: NextEventSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1
FROM events
WHERE review_session_id = ?
`

func (q *Queries) NextEventSequence(ctx context.Context, reviewSessionID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextEventSequence, reviewSessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
