// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence_graphs.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createCallPath = `-- name: CreateCallPath :one
INSERT INTO call_paths (
  id,
  evidence_graph_id,
  label,
  confidence,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, evidence_graph_id, label, confidence, created_at
`

type CreateCallPathParams struct {
	ID              string         `json:"id"`
	EvidenceGraphID string         `json:"evidence_graph_id"`
	Label           sql.NullString `json:"label"`
	Confidence      float64        `json:"confidence"`
	CreatedAt       string         `json:"created_at"`
}

func (q *Queries) CreateCallPath(ctx context.Context, arg CreateCallPathParams) (CallPath, error) {
	row := q.db.QueryRowContext(ctx, createCallPath,
		arg.ID,
		arg.EvidenceGraphID,
		arg.Label,
		arg.Confidence,
		arg.CreatedAt,
	)
	var i CallPath
	err := row.Scan(
		&i.ID,
		&i.EvidenceGraphID,
		&i.Label,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const createCallPathStep = `-- name: CreateCallPathStep :one
INSERT INTO call_path_steps (
  id,
  call_path_id,
  step_index,
  node_id,
  path,
  start_line,
  end_line,
  label
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, call_path_id, step_index, node_id, path, start_line, end_line, label
`

type CreateCallPathStepParams struct {
	ID         string         `json:"id"`
	CallPathID string         `json:"call_path_id"`
	StepIndex  int64          `json:"step_index"`
	NodeID     sql.NullString `json:"node_id"`
	Path       sql.NullString `json:"path"`
	StartLine  sql.NullInt64  `json:"start_line"`
	EndLine    sql.NullInt64  `json:"end_line"`
	Label      string         `json:"label"`
}

func (q *Queries) CreateCallPathStep(ctx context.Context, arg CreateCallPathStepParams) (CallPathStep, error) {
	row := q.db.QueryRowContext(ctx, createCallPathStep,
		arg.ID,
		arg.CallPathID,
		arg.StepIndex,
		arg.NodeID,
		arg.Path,
		arg.StartLine,
		arg.EndLine,
		arg.Label,
	)
	var i CallPathStep
	err := row.Scan(
		&i.ID,
		&i.CallPathID,
		&i.StepIndex,
		&i.NodeID,
		&i.Path,
		&i.StartLine,
		&i.EndLine,
		&i.Label,
	)
	return i, err
}

const createEvidenceEdge = `-- name: CreateEvidenceEdge :one
INSERT INTO evidence_edges (
  id,
  evidence_graph_id,
  source_node_id,
  target_node_id,
  kind,
  status,
  label,
  confidence,
  metadata_json
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, evidence_graph_id, source_node_id, target_node_id, kind, status, label, confidence, metadata_json
`

type CreateEvidenceEdgeParams struct {
	ID              string         `json:"id"`
	EvidenceGraphID string         `json:"evidence_graph_id"`
	SourceNodeID    string         `json:"source_node_id"`
	TargetNodeID    string         `json:"target_node_id"`
	Kind            string         `json:"kind"`
	Status          string         `json:"status"`
	Label           sql.NullString `json:"label"`
	Confidence      float64        `json:"confidence"`
	MetadataJson    string         `json:"metadata_json"`
}

func (q *Queries) CreateEvidenceEdge(ctx context.Context, arg CreateEvidenceEdgeParams) (EvidenceEdge, error) {
	row := q.db.QueryRowContext(ctx, createEvidenceEdge,
		arg.ID,
		arg.EvidenceGraphID,
		arg.SourceNodeID,
		arg.TargetNodeID,
		arg.Kind,
		arg.Status,
		arg.Label,
		arg.Confidence,
		arg.MetadataJson,
	)
	var i EvidenceEdge
	err := row.Scan(
		&i.ID,
		&i.EvidenceGraphID,
		&i.SourceNodeID,
		&i.TargetNodeID,
		&i.Kind,
		&i.Status,
		&i.Label,
		&i.Confidence,
		&i.MetadataJson,
	)
	return i, err
}

const createEvidenceGraph = `-- name: CreateEvidenceGraph :one
INSERT INTO evidence_graphs (
  id,
  finding_id,
  review_session_id,
  status,
  layout_json,
  summary,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, finding_id, review_session_id, status, layout_json, summary, created_at, updated_at
`

type CreateEvidenceGraphParams struct {
	ID              string         `json:"id"`
	FindingID       string         `json:"finding_id"`
	ReviewSessionID string         `json:"review_session_id"`
	Status          string         `json:"status"`
	LayoutJson      string         `json:"layout_json"`
	Summary         sql.NullString `json:"summary"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

func (q *Queries) CreateEvidenceGraph(ctx context.Context, arg CreateEvidenceGraphParams) (EvidenceGraph, error) {
	row := q.db.QueryRowContext(ctx, createEvidenceGraph,
		arg.ID,
		arg.FindingID,
		arg.ReviewSessionID,
		arg.Status,
		arg.LayoutJson,
		arg.Summary,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EvidenceGraph
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ReviewSessionID,
		&i.Status,
		&i.LayoutJson,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEvidenceItem = `-- name: CreateEvidenceItem :one
INSERT INTO evidence_items (
  id,
  finding_id,
  kind,
  title,
  summary,
  path,
  start_line,
  end_line,
  artifact_id,
  confidence,
  metadata_json,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, finding_id, kind, title, summary, path, start_line, end_line, artifact_id, confidence, metadata_json, created_at
`

type CreateEvidenceItemParams struct {
	ID           string         `json:"id"`
	FindingID    string         `json:"finding_id"`
	Kind         string         `json:"kind"`
	Title        string         `json:"title"`
	Summary      string         `json:"summary"`
	Path         sql.NullString `json:"path"`
	StartLine    sql.NullInt64  `json:"start_line"`
	EndLine      sql.NullInt64  `json:"end_line"`
	ArtifactID   sql.NullString `json:"artifact_id"`
	Confidence   float64        `json:"confidence"`
	MetadataJson string         `json:"metadata_json"`
	CreatedAt    string         `json:"created_at"`
}

func (q *Queries) CreateEvidenceItem(ctx context.Context, arg CreateEvidenceItemParams) (EvidenceItem, error) {
	row := q.db.QueryRowContext(ctx, createEvidenceItem,
		arg.ID,
		arg.FindingID,
		arg.Kind,
		arg.Title,
		arg.Summary,
		arg.Path,
		arg.StartLine,
		arg.EndLine,
		arg.ArtifactID,
		arg.Confidence,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	var i EvidenceItem
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.Path,
		&i.StartLine,
		&i.EndLine,
		&i.ArtifactID,
		&i.Confidence,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const createEvidenceNode = `-- name: CreateEvidenceNode :one
INSERT INTO evidence_nodes (
  id,
  evidence_graph_id,
  kind,
  label,
  path,
  symbol,
  start_line,
  end_line,
  evidence_item_id,
  confidence,
  metadata_json
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, evidence_graph_id, kind, label, path, symbol, start_line, end_line, evidence_item_id, confidence, metadata_json
`

type CreateEvidenceNodeParams struct {
	ID              string         `json:"id"`
	EvidenceGraphID string         `json:"evidence_graph_id"`
	Kind            string         `json:"kind"`
	Label           string         `json:"label"`
	Path            sql.NullString `json:"path"`
	Symbol          sql.NullString `json:"symbol"`
	StartLine       sql.NullInt64  `json:"start_line"`
	EndLine         sql.NullInt64  `json:"end_line"`
	EvidenceItemID  sql.NullString `json:"evidence_item_id"`
	Confidence      float64        `json:"confidence"`
	MetadataJson    string         `json:"metadata_json"`
}

func (q *Queries) CreateEvidenceNode(ctx context.Context, arg CreateEvidenceNodeParams) (EvidenceNode, error) {
	row := q.db.QueryRowContext(ctx, createEvidenceNode,
		arg.ID,
		arg.EvidenceGraphID,
		arg.Kind,
		arg.Label,
		arg.Path,
		arg.Symbol,
		arg.StartLine,
		arg.EndLine,
		arg.EvidenceItemID,
		arg.Confidence,
		arg.MetadataJson,
	)
	var i EvidenceNode
	err := row.Scan(
		&i.ID,
		&i.EvidenceGraphID,
		&i.Kind,
		&i.Label,
		&i.Path,
		&i.Symbol,
		&i.StartLine,
		&i.EndLine,
		&i.EvidenceItemID,
		&i.Confidence,
		&i.MetadataJson,
	)
	return i, err
}

const deleteCallPath = `-- name: DeleteCallPath :exec
DELETE FROM call_paths
WHERE id = ?
`

func (q *Queries) DeleteCallPath(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCallPath, id)
	return err
}

const deleteEvidenceEdge = `-- name: DeleteEvidenceEdge :exec
DELETE FROM evidence_edges
WHERE id = ?
`

func (q *Queries) DeleteEvidenceEdge(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEvidenceEdge, id)
	return err
}

const deleteEvidenceGraph = `-- name: DeleteEvidenceGraph :exec
DELETE FROM evidence_graphs
WHERE id = ?
`

func (q *Queries) DeleteEvidenceGraph(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEvidenceGraph, id)
	return err
}

const deleteEvidenceItem = `-- name: DeleteEvidenceItem :exec
DELETE FROM evidence_items
WHERE id = ?
`

func (q *Queries) DeleteEvidenceItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEvidenceItem, id)
	return err
}

const deleteEvidenceNode = `-- name: DeleteEvidenceNode :exec
DELETE FROM evidence_nodes
WHERE id = ?
`

func (q *Queries) DeleteEvidenceNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEvidenceNode, id)
	return err
}

const getEvidenceGraph = `-- name: GetEvidenceGraph :one
SELECT id, finding_id, review_session_id, status, layout_json, summary, created_at, updated_at
FROM evidence_graphs
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetEvidenceGraph(ctx context.Context, id string) (EvidenceGraph, error) {
	row := q.db.QueryRowContext(ctx, getEvidenceGraph, id)
	var i EvidenceGraph
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ReviewSessionID,
		&i.Status,
		&i.LayoutJson,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEvidenceGraphByFinding = `-- name: GetEvidenceGraphByFinding :one
SELECT id, finding_id, review_session_id, status, layout_json, summary, created_at, updated_at
FROM evidence_graphs
WHERE finding_id = ?
LIMIT 1
`

func (q *Queries) GetEvidenceGraphByFinding(ctx context.Context, findingID string) (EvidenceGraph, error) {
	row := q.db.QueryRowContext(ctx, getEvidenceGraphByFinding, findingID)
	var i EvidenceGraph
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ReviewSessionID,
		&i.Status,
		&i.LayoutJson,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEvidenceItem = `-- name: GetEvidenceItem :one
SELECT id, finding_id, kind, title, summary, path, start_line, end_line, artifact_id, confidence, metadata_json, created_at
FROM evidence_items
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetEvidenceItem(ctx context.Context, id string) (EvidenceItem, error) {
	row := q.db.QueryRowContext(ctx, getEvidenceItem, id)
	var i EvidenceItem
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.Path,
		&i.StartLine,
		&i.EndLine,
		&i.ArtifactID,
		&i.Confidence,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const getEvidenceNode = `-- name: GetEvidenceNode :one
SELECT id, evidence_graph_id, kind, label, path, symbol, start_line, end_line, evidence_item_id, confidence, metadata_json
FROM evidence_nodes
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetEvidenceNode(ctx context.Context, id string) (EvidenceNode, error) {
	row := q.db.QueryRowContext(ctx, getEvidenceNode, id)
	var i EvidenceNode
	err := row.Scan(
		&i.ID,
		&i.EvidenceGraphID,
		&i.Kind,
		&i.Label,
		&i.Path,
		&i.Symbol,
		&i.StartLine,
		&i.EndLine,
		&i.EvidenceItemID,
		&i.Confidence,
		&i.MetadataJson,
	)
	return i, err
}

const listCallPathStepsByCallPath = `-- name: ListCallPathStepsByCallPath :many
SELECT id, call_path_id, step_index, node_id, path, start_line, end_line, label
FROM call_path_steps
WHERE call_path_id = ?
ORDER BY step_index ASC
`

func (q *Queries) ListCallPathStepsByCallPath(ctx context.Context, callPathID string) ([]CallPathStep, error) {
	rows, err := q.db.QueryContext(ctx, listCallPathStepsByCallPath, callPathID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CallPathStep{}
	for rows.Next() {
		var i CallPathStep
		if err := rows.Scan(
			&i.ID,
			&i.CallPathID,
			&i.StepIndex,
			&i.NodeID,
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallPathsByGraph = `-- name: ListCallPathsByGraph :many
SELECT id, evidence_graph_id, label, confidence, created_at
FROM call_paths
WHERE evidence_graph_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListCallPathsByGraph(ctx context.Context, evidenceGraphID string) ([]CallPath, error) {
	rows, err := q.db.QueryContext(ctx, listCallPathsByGraph, evidenceGraphID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CallPath{}
	for rows.Next() {
		var i CallPath
		if err := rows.Scan(
			&i.ID,
			&i.EvidenceGraphID,
			&i.Label,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceEdgesByGraph = `-- name: ListEvidenceEdgesByGraph :many
SELECT id, evidence_graph_id, source_node_id, target_node_id, kind, status, label, confidence, metadata_json
FROM evidence_edges
WHERE evidence_graph_id = ?
ORDER BY kind ASC, id ASC
`

func (q *Queries) ListEvidenceEdgesByGraph(ctx context.Context, evidenceGraphID string) ([]EvidenceEdge, error) {
	rows, err := q.db.QueryContext(ctx, listEvidenceEdgesByGraph, evidenceGraphID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvidenceEdge{}
	for rows.Next() {
		var i EvidenceEdge
		if err := rows.Scan(
			&i.ID,
			&i.EvidenceGraphID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.Kind,
			&i.Status,
			&i.Label,
			&i.Confidence,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceItemsByFinding = `-- name: ListEvidenceItemsByFinding :many
SELECT id, finding_id, kind, title, summary, path, start_line, end_line, artifact_id, confidence, metadata_json, created_at
FROM evidence_items
WHERE finding_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListEvidenceItemsByFinding(ctx context.Context, findingID string) ([]EvidenceItem, error) {
	rows, err := q.db.QueryContext(ctx, listEvidenceItemsByFinding, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvidenceItem{}
	for rows.Next() {
		var i EvidenceItem
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.Kind,
			&i.Title,
			&i.Summary,
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.ArtifactID,
			&i.Confidence,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceItemsBySession = `-- name: ListEvidenceItemsBySession :many
SELECT ei.id, ei.finding_id, ei.kind, ei.title, ei.summary, ei.path, ei.start_line, ei.end_line, ei.artifact_id, ei.confidence, ei.metadata_json, ei.created_at
FROM evidence_items ei
JOIN findings f ON f.id = ei.finding_id
WHERE f.review_session_id = ?
ORDER BY ei.finding_id ASC, ei.confidence DESC, ei.created_at ASC, ei.id ASC
`

func (q *Queries) ListEvidenceItemsBySession(ctx context.Context, reviewSessionID string) ([]EvidenceItem, error) {
	rows, err := q.db.QueryContext(ctx, listEvidenceItemsBySession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvidenceItem{}
	for rows.Next() {
		var i EvidenceItem
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.Kind,
			&i.Title,
			&i.Summary,
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.ArtifactID,
			&i.Confidence,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceNodesByGraph = `-- name: ListEvidenceNodesByGraph :many
SELECT id, evidence_graph_id, kind, label, path, symbol, start_line, end_line, evidence_item_id, confidence, metadata_json
FROM evidence_nodes
WHERE evidence_graph_id = ?
ORDER BY kind ASC, label ASC
`

func (q *Queries) ListEvidenceNodesByGraph(ctx context.Context, evidenceGraphID string) ([]EvidenceNode, error) {
	rows, err := q.db.QueryContext(ctx, listEvidenceNodesByGraph, evidenceGraphID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvidenceNode{}
	for rows.Next() {
		var i EvidenceNode
		if err := rows.Scan(
			&i.ID,
			&i.EvidenceGraphID,
			&i.Kind,
			&i.Label,
			&i.Path,
			&i.Symbol,
			&i.StartLine,
			&i.EndLine,
			&i.EvidenceItemID,
			&i.Confidence,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCallPath = `-- name: UpdateCallPath :one
UPDATE call_paths
SET
  label = ?,
  confidence = ?
WHERE id = ?
RETURNING id, evidence_graph_id, label, confidence, created_at
`

type UpdateCallPathParams struct {
	Label      sql.NullString `json:"label"`
	Confidence float64        `json:"confidence"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateCallPath(ctx context.Context, arg UpdateCallPathParams) (CallPath, error) {
	row := q.db.QueryRowContext(ctx, updateCallPath, arg.Label, arg.Confidence, arg.ID)
	var i CallPath
	err := row.Scan(
		&i.ID,
		&i.EvidenceGraphID,
		&i.Label,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const updateEvidenceEdge = `-- name: UpdateEvidenceEdge :one
UPDATE evidence_edges
SET
  kind = ?,
  status = ?,
  label = ?,
  confidence = ?,
  metadata_json = ?
WHERE id = ?
RETURNING id, evidence_graph_id, source_node_id, target_node_id, kind, status, label, confidence, metadata_json
`

type UpdateEvidenceEdgeParams struct {
	Kind         string         `json:"kind"`
	Status       string         `json:"status"`
	Label        sql.NullString `json:"label"`
	Confidence   float64        `json:"confidence"`
	MetadataJson string         `json:"metadata_json"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateEvidenceEdge(ctx context.Context, arg UpdateEvidenceEdgeParams) (EvidenceEdge, error) {
	row := q.db.QueryRowContext(ctx, updateEvidenceEdge,
		arg.Kind,
		arg.Status,
		arg.Label,
		arg.Confidence,
		arg.MetadataJson,
		arg.ID,
	)
	var i EvidenceEdge
	err := row.Scan(
		&i.ID,
		&i.EvidenceGraphID,
		&i.SourceNodeID,
		&i.TargetNodeID,
		&i.Kind,
		&i.Status,
		&i.Label,
		&i.Confidence,
		&i.MetadataJson,
	)
	return i, err
}

const updateEvidenceGraph = `-- name: UpdateEvidenceGraph :one
UPDATE evidence_graphs
SET
  status = ?,
  layout_json = ?,
  summary = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, finding_id, review_session_id, status, layout_json, summary, created_at, updated_at
`

type UpdateEvidenceGraphParams struct {
	Status     string         `json:"status"`
	LayoutJson string         `json:"layout_json"`
	Summary    sql.NullString `json:"summary"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateEvidenceGraph(ctx context.Context, arg UpdateEvidenceGraphParams) (EvidenceGraph, error) {
	row := q.db.QueryRowContext(ctx, updateEvidenceGraph,
		arg.Status,
		arg.LayoutJson,
		arg.Summary,
		arg.UpdatedAt,
		arg.ID,
	)
	var i EvidenceGraph
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ReviewSessionID,
		&i.Status,
		&i.LayoutJson,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEvidenceItem = `-- name: UpdateEvidenceItem :one
UPDATE evidence_items
SET
  kind = ?,
  title = ?,
  summary = ?,
  path = ?,
  start_line = ?,
  end_line = ?,
  artifact_id = ?,
  confidence = ?,
  metadata_json = ?
WHERE id = ?
RETURNING id, finding_id, kind, title, summary, path, start_line, end_line, artifact_id, confidence, metadata_json, created_at
`

type UpdateEvidenceItemParams struct {
	Kind         string         `json:"kind"`
	Title        string         `json:"title"`
	Summary      string         `json:"summary"`
	Path         sql.NullString `json:"path"`
	StartLine    sql.NullInt64  `json:"start_line"`
	EndLine      sql.NullInt64  `json:"end_line"`
	ArtifactID   sql.NullString `json:"artifact_id"`
	Confidence   float64        `json:"confidence"`
	MetadataJson string         `json:"metadata_json"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateEvidenceItem(ctx context.Context, arg UpdateEvidenceItemParams) (EvidenceItem, error) {
	row := q.db.QueryRowContext(ctx, updateEvidenceItem,
		arg.Kind,
		arg.Title,
		arg.Summary,
		arg.Path,
		arg.StartLine,
		arg.EndLine,
		arg.ArtifactID,
		arg.Confidence,
		arg.MetadataJson,
		arg.ID,
	)
	var i EvidenceItem
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.Path,
		&i.StartLine,
		&i.EndLine,
		&i.ArtifactID,
		&i.Confidence,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const updateEvidenceNode = `-- name: UpdateEvidenceNode :one
UPDATE evidence_nodes
SET
  kind = ?,
  label = ?,
  path = ?,
  symbol = ?,
  start_line = ?,
  end_line = ?,
  evidence_item_id = ?,
  confidence = ?,
  metadata_json = ?
WHERE id = ?
RETURNING id, evidence_graph_id, kind, label, path, symbol, start_line, end_line, evidence_item_id, confidence, metadata_json
`

type UpdateEvidenceNodeParams struct {
	Kind           string         `json:"kind"`
	Label          string         `json:"label"`
	Path           sql.NullString `json:"path"`
	Symbol         sql.NullString `json:"symbol"`
	StartLine      sql.NullInt64  `json:"start_line"`
	EndLine        sql.NullInt64  `json:"end_line"`
	EvidenceItemID sql.NullString `json:"evidence_item_id"`
	Confidence     float64        `json:"confidence"`
	MetadataJson   string         `json:"metadata_json"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateEvidenceNode(ctx context.Context, arg UpdateEvidenceNodeParams) (EvidenceNode, error) {
	row := q.db.QueryRowContext(ctx, updateEvidenceNode,
		arg.Kind,
		arg.Label,
		arg.Path,
		arg.Symbol,
		arg.StartLine,
		arg.EndLine,
		arg.EvidenceItemID,
		arg.Confidence,
		arg.MetadataJson,
		arg.ID,
	)
	var i EvidenceNode
	err := row.Scan(
		&i.ID,
		&i.EvidenceGraphID,
		&i.Kind,
		&i.Label,
		&i.Path,
		&i.Symbol,
		&i.StartLine,
		&i.EndLine,
		&i.EvidenceItemID,
		&i.Confidence,
		&i.MetadataJson,
	)
	return i, err
}
