// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createFinding = `-- name: CreateFinding :one
INSERT INTO findings (
  id,
  review_session_id,
  canonical_claim,
  category,
  severity,
  confidence,
  verification_status,
  decision_status,
  primary_path,
  primary_start_line,
  primary_end_line,
  evidence_summary,
  counter_evidence_summary,
  suggested_fix,
  draft_comment,
  fingerprint,
  merged_from_count,
  introduced_in_sha,
  first_seen_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON CONFLICT(review_session_id, fingerprint)
DO UPDATE SET
  canonical_claim = excluded.canonical_claim,
  category = excluded.category,
  severity = excluded.severity,
  confidence = excluded.confidence,
  verification_status = excluded.verification_status,
  primary_path = excluded.primary_path,
  primary_start_line = excluded.primary_start_line,
  primary_end_line = excluded.primary_end_line,
  evidence_summary = excluded.evidence_summary,
  counter_evidence_summary = excluded.counter_evidence_summary,
  suggested_fix = excluded.suggested_fix,
  draft_comment = excluded.draft_comment,
  merged_from_count = excluded.merged_from_count,
  introduced_in_sha = excluded.introduced_in_sha,
  updated_at = excluded.updated_at
RETURNING id, review_session_id, canonical_claim, category, severity, confidence, verification_status, decision_status, primary_path, primary_start_line, primary_end_line, evidence_summary, counter_evidence_summary, suggested_fix, draft_comment, fingerprint, merged_from_count, introduced_in_sha, first_seen_at, updated_at
`

type CreateFindingParams struct {
	ID                     string         `json:"id"`
	ReviewSessionID        string         `json:"review_session_id"`
	CanonicalClaim         string         `json:"canonical_claim"`
	Category               string         `json:"category"`
	Severity               string         `json:"severity"`
	Confidence             float64        `json:"confidence"`
	VerificationStatus     string         `json:"verification_status"`
	DecisionStatus         string         `json:"decision_status"`
	PrimaryPath            sql.NullString `json:"primary_path"`
	PrimaryStartLine       sql.NullInt64  `json:"primary_start_line"`
	PrimaryEndLine         sql.NullInt64  `json:"primary_end_line"`
	EvidenceSummary        sql.NullString `json:"evidence_summary"`
	CounterEvidenceSummary sql.NullString `json:"counter_evidence_summary"`
	SuggestedFix           sql.NullString `json:"suggested_fix"`
	DraftComment           sql.NullString `json:"draft_comment"`
	Fingerprint            string         `json:"fingerprint"`
	MergedFromCount        int64          `json:"merged_from_count"`
	IntroducedInSha        sql.NullString `json:"introduced_in_sha"`
	FirstSeenAt            string         `json:"first_seen_at"`
	UpdatedAt              string         `json:"updated_at"`
}

func (q *Queries) CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, createFinding,
		arg.ID,
		arg.ReviewSessionID,
		arg.CanonicalClaim,
		arg.Category,
		arg.Severity,
		arg.Confidence,
		arg.VerificationStatus,
		arg.DecisionStatus,
		arg.PrimaryPath,
		arg.PrimaryStartLine,
		arg.PrimaryEndLine,
		arg.EvidenceSummary,
		arg.CounterEvidenceSummary,
		arg.SuggestedFix,
		arg.DraftComment,
		arg.Fingerprint,
		arg.MergedFromCount,
		arg.IntroducedInSha,
		arg.FirstSeenAt,
		arg.UpdatedAt,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.CanonicalClaim,
		&i.Category,
		&i.Severity,
		&i.Confidence,
		&i.VerificationStatus,
		&i.DecisionStatus,
		&i.PrimaryPath,
		&i.PrimaryStartLine,
		&i.PrimaryEndLine,
		&i.EvidenceSummary,
		&i.CounterEvidenceSummary,
		&i.SuggestedFix,
		&i.DraftComment,
		&i.Fingerprint,
		&i.MergedFromCount,
		&i.IntroducedInSha,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFindingCandidate = `-- name: CreateFindingCandidate :one
INSERT INTO finding_candidates (
  id,
  review_session_id,
  agent_run_id,
  raw_artifact_id,
  category,
  severity,
  confidence,
  claim,
  primary_path,
  primary_start_line,
  primary_end_line,
  locations_json,
  evidence_json,
  suggested_fix,
  draft_comment,
  fingerprint,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON CONFLICT(agent_run_id, fingerprint) WHERE fingerprint IS NOT NULL AND fingerprint <> ''
DO UPDATE SET
  id = finding_candidates.id
RETURNING id, review_session_id, agent_run_id, raw_artifact_id, category, severity, confidence, claim, primary_path, primary_start_line, primary_end_line, locations_json, evidence_json, suggested_fix, draft_comment, fingerprint, created_at
`

type CreateFindingCandidateParams struct {
	ID               string         `json:"id"`
	ReviewSessionID  string         `json:"review_session_id"`
	AgentRunID       string         `json:"agent_run_id"`
	RawArtifactID    sql.NullString `json:"raw_artifact_id"`
	Category         string         `json:"category"`
	Severity         string         `json:"severity"`
	Confidence       float64        `json:"confidence"`
	Claim            string         `json:"claim"`
	PrimaryPath      sql.NullString `json:"primary_path"`
	PrimaryStartLine sql.NullInt64  `json:"primary_start_line"`
	PrimaryEndLine   sql.NullInt64  `json:"primary_end_line"`
	LocationsJson    string         `json:"locations_json"`
	EvidenceJson     string         `json:"evidence_json"`
	SuggestedFix     sql.NullString `json:"suggested_fix"`
	DraftComment     sql.NullString `json:"draft_comment"`
	Fingerprint      sql.NullString `json:"fingerprint"`
	CreatedAt        string         `json:"created_at"`
}

func (q *Queries) CreateFindingCandidate(ctx context.Context, arg CreateFindingCandidateParams) (FindingCandidate, error) {
	row := q.db.QueryRowContext(ctx, createFindingCandidate,
		arg.ID,
		arg.ReviewSessionID,
		arg.AgentRunID,
		arg.RawArtifactID,
		arg.Category,
		arg.Severity,
		arg.Confidence,
		arg.Claim,
		arg.PrimaryPath,
		arg.PrimaryStartLine,
		arg.PrimaryEndLine,
		arg.LocationsJson,
		arg.EvidenceJson,
		arg.SuggestedFix,
		arg.DraftComment,
		arg.Fingerprint,
		arg.CreatedAt,
	)
	var i FindingCandidate
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentRunID,
		&i.RawArtifactID,
		&i.Category,
		&i.Severity,
		&i.Confidence,
		&i.Claim,
		&i.PrimaryPath,
		&i.PrimaryStartLine,
		&i.PrimaryEndLine,
		&i.LocationsJson,
		&i.EvidenceJson,
		&i.SuggestedFix,
		&i.DraftComment,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const createHumanDecision = `-- name: CreateHumanDecision :one
INSERT INTO human_decisions (
  id,
  finding_id,
  review_session_id,
  decision,
  reason,
  metadata_json,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, finding_id, review_session_id, decision, reason, metadata_json, created_at
`

type CreateHumanDecisionParams struct {
	ID              string         `json:"id"`
	FindingID       string         `json:"finding_id"`
	ReviewSessionID string         `json:"review_session_id"`
	Decision        string         `json:"decision"`
	Reason          sql.NullString `json:"reason"`
	MetadataJson    string         `json:"metadata_json"`
	CreatedAt       string         `json:"created_at"`
}

func (q *Queries) CreateHumanDecision(ctx context.Context, arg CreateHumanDecisionParams) (HumanDecision, error) {
	row := q.db.QueryRowContext(ctx, createHumanDecision,
		arg.ID,
		arg.FindingID,
		arg.ReviewSessionID,
		arg.Decision,
		arg.Reason,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	var i HumanDecision
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ReviewSessionID,
		&i.Decision,
		&i.Reason,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFinding = `-- name: DeleteFinding :exec
DELETE FROM findings
WHERE id = ?
`

func (q *Queries) DeleteFinding(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFinding, id)
	return err
}

const deleteFindingCandidate = `-- name: DeleteFindingCandidate :exec
DELETE FROM finding_candidates
WHERE id = ?
`

func (q *Queries) DeleteFindingCandidate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFindingCandidate, id)
	return err
}

const getFinding = `-- name: GetFinding :one
SELECT id, review_session_id, canonical_claim, category, severity, confidence, verification_status, decision_status, primary_path, primary_start_line, primary_end_line, evidence_summary, counter_evidence_summary, suggested_fix, draft_comment, fingerprint, merged_from_count, introduced_in_sha, first_seen_at, updated_at
FROM findings
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetFinding(ctx context.Context, id string) (Finding, error) {
	row := q.db.QueryRowContext(ctx, getFinding, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.CanonicalClaim,
		&i.Category,
		&i.Severity,
		&i.Confidence,
		&i.VerificationStatus,
		&i.DecisionStatus,
		&i.PrimaryPath,
		&i.PrimaryStartLine,
		&i.PrimaryEndLine,
		&i.EvidenceSummary,
		&i.CounterEvidenceSummary,
		&i.SuggestedFix,
		&i.DraftComment,
		&i.Fingerprint,
		&i.MergedFromCount,
		&i.IntroducedInSha,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFindingCandidate = `-- name: GetFindingCandidate :one
SELECT id, review_session_id, agent_run_id, raw_artifact_id, category, severity, confidence, claim, primary_path, primary_start_line, primary_end_line, locations_json, evidence_json, suggested_fix, draft_comment, fingerprint, created_at
FROM finding_candidates
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetFindingCandidate(ctx context.Context, id string) (FindingCandidate, error) {
	row := q.db.QueryRowContext(ctx, getFindingCandidate, id)
	var i FindingCandidate
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.AgentRunID,
		&i.RawArtifactID,
		&i.Category,
		&i.Severity,
		&i.Confidence,
		&i.Claim,
		&i.PrimaryPath,
		&i.PrimaryStartLine,
		&i.PrimaryEndLine,
		&i.LocationsJson,
		&i.EvidenceJson,
		&i.SuggestedFix,
		&i.DraftComment,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const linkFindingCandidate = `-- name: LinkFindingCandidate :exec
INSERT INTO finding_candidate_links (
  finding_id,
  finding_candidate_id,
  relation
) VALUES (
  ?,
  ?,
  ?
)
ON CONFLICT(finding_id, finding_candidate_id)
DO UPDATE SET relation = excluded.relation
`

type LinkFindingCandidateParams struct {
	FindingID          string `json:"finding_id"`
	FindingCandidateID string `json:"finding_candidate_id"`
	Relation           string `json:"relation"`
}

func (q *Queries) LinkFindingCandidate(ctx context.Context, arg LinkFindingCandidateParams) error {
	_, err := q.db.ExecContext(ctx, linkFindingCandidate, arg.FindingID, arg.FindingCandidateID, arg.Relation)
	return err
}

const listFindingCandidateLinks = `-- name: ListFindingCandidateLinks :many
SELECT finding_id, finding_candidate_id, relation
FROM finding_candidate_links
WHERE finding_id = ?
ORDER BY finding_candidate_id ASC
`

func (q *Queries) ListFindingCandidateLinks(ctx context.Context, findingID string) ([]FindingCandidateLink, error) {
	rows, err := q.db.QueryContext(ctx, listFindingCandidateLinks, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingCandidateLink{}
	for rows.Next() {
		var i FindingCandidateLink
		if err := rows.Scan(&i.FindingID, &i.FindingCandidateID, &i.Relation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingCandidatesBySession = `-- name: ListFindingCandidatesBySession :many
SELECT id, review_session_id, agent_run_id, raw_artifact_id, category, severity, confidence, claim, primary_path, primary_start_line, primary_end_line, locations_json, evidence_json, suggested_fix, draft_comment, fingerprint, created_at
FROM finding_candidates
WHERE review_session_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListFindingCandidatesBySession(ctx context.Context, reviewSessionID string) ([]FindingCandidate, error) {
	rows, err := q.db.QueryContext(ctx, listFindingCandidatesBySession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingCandidate{}
	for rows.Next() {
		var i FindingCandidate
		if err := rows.Scan(
			&i.ID,
			&i.ReviewSessionID,
			&i.AgentRunID,
			&i.RawArtifactID,
			&i.Category,
			&i.Severity,
			&i.Confidence,
			&i.Claim,
			&i.PrimaryPath,
			&i.PrimaryStartLine,
			&i.PrimaryEndLine,
			&i.LocationsJson,
			&i.EvidenceJson,
			&i.SuggestedFix,
			&i.DraftComment,
			&i.Fingerprint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsBySession = `-- name: ListFindingsBySession :many
SELECT id, review_session_id, canonical_claim, category, severity, confidence, verification_status, decision_status, primary_path, primary_start_line, primary_end_line, evidence_summary, counter_evidence_summary, suggested_fix, draft_comment, fingerprint, merged_from_count, introduced_in_sha, first_seen_at, updated_at
FROM findings
WHERE review_session_id = ?
ORDER BY updated_at DESC, id ASC
`

func (q *Queries) ListFindingsBySession(ctx context.Context, reviewSessionID string) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsBySession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewSessionID,
			&i.CanonicalClaim,
			&i.Category,
			&i.Severity,
			&i.Confidence,
			&i.VerificationStatus,
			&i.DecisionStatus,
			&i.PrimaryPath,
			&i.PrimaryStartLine,
			&i.PrimaryEndLine,
			&i.EvidenceSummary,
			&i.CounterEvidenceSummary,
			&i.SuggestedFix,
			&i.DraftComment,
			&i.Fingerprint,
			&i.MergedFromCount,
			&i.IntroducedInSha,
			&i.FirstSeenAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHumanDecisionsByFinding = `-- name: ListHumanDecisionsByFinding :many
SELECT id, finding_id, review_session_id, decision, reason, metadata_json, created_at
FROM human_decisions
WHERE finding_id = ?
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListHumanDecisionsByFinding(ctx context.Context, findingID string) ([]HumanDecision, error) {
	rows, err := q.db.QueryContext(ctx, listHumanDecisionsByFinding, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HumanDecision{}
	for rows.Next() {
		var i HumanDecision
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.ReviewSessionID,
			&i.Decision,
			&i.Reason,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHumanDecisionsBySession = `-- name: ListHumanDecisionsBySession :many
SELECT id, finding_id, review_session_id, decision, reason, metadata_json, created_at
FROM human_decisions
WHERE review_session_id = ?
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListHumanDecisionsBySession(ctx context.Context, reviewSessionID string) ([]HumanDecision, error) {
	rows, err := q.db.QueryContext(ctx, listHumanDecisionsBySession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HumanDecision{}
	for rows.Next() {
		var i HumanDecision
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.ReviewSessionID,
			&i.Decision,
			&i.Reason,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFinding = `-- name: UpdateFinding :one
UPDATE findings
SET
  canonical_claim = ?,
  category = ?,
  severity = ?,
  confidence = ?,
  primary_path = ?,
  primary_start_line = ?,
  primary_end_line = ?,
  evidence_summary = ?,
  counter_evidence_summary = ?,
  suggested_fix = ?,
  draft_comment = ?,
  merged_from_count = ?,
  introduced_in_sha = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, review_session_id, canonical_claim, category, severity, confidence, verification_status, decision_status, primary_path, primary_start_line, primary_end_line, evidence_summary, counter_evidence_summary, suggested_fix, draft_comment, fingerprint, merged_from_count, introduced_in_sha, first_seen_at, updated_at
`

type UpdateFindingParams struct {
	CanonicalClaim         string         `json:"canonical_claim"`
	Category               string         `json:"category"`
	Severity               string         `json:"severity"`
	Confidence             float64        `json:"confidence"`
	PrimaryPath            sql.NullString `json:"primary_path"`
	PrimaryStartLine       sql.NullInt64  `json:"primary_start_line"`
	PrimaryEndLine         sql.NullInt64  `json:"primary_end_line"`
	EvidenceSummary        sql.NullString `json:"evidence_summary"`
	CounterEvidenceSummary sql.NullString `json:"counter_evidence_summary"`
	SuggestedFix           sql.NullString `json:"suggested_fix"`
	DraftComment           sql.NullString `json:"draft_comment"`
	MergedFromCount        int64          `json:"merged_from_count"`
	IntroducedInSha        sql.NullString `json:"introduced_in_sha"`
	UpdatedAt              string         `json:"updated_at"`
	ID                     string         `json:"id"`
}

func (q *Queries) UpdateFinding(ctx context.Context, arg UpdateFindingParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, updateFinding,
		arg.CanonicalClaim,
		arg.Category,
		arg.Severity,
		arg.Confidence,
		arg.PrimaryPath,
		arg.PrimaryStartLine,
		arg.PrimaryEndLine,
		arg.EvidenceSummary,
		arg.CounterEvidenceSummary,
		arg.SuggestedFix,
		arg.DraftComment,
		arg.MergedFromCount,
		arg.IntroducedInSha,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.CanonicalClaim,
		&i.Category,
		&i.Severity,
		&i.Confidence,
		&i.VerificationStatus,
		&i.DecisionStatus,
		&i.PrimaryPath,
		&i.PrimaryStartLine,
		&i.PrimaryEndLine,
		&i.EvidenceSummary,
		&i.CounterEvidenceSummary,
		&i.SuggestedFix,
		&i.DraftComment,
		&i.Fingerprint,
		&i.MergedFromCount,
		&i.IntroducedInSha,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFindingDecisionStatus = `-- name: UpdateFindingDecisionStatus :one
UPDATE findings
SET decision_status = ?, updated_at = ?
WHERE id = ?
RETURNING id, review_session_id, canonical_claim, category, severity, confidence, verification_status, decision_status, primary_path, primary_start_line, primary_end_line, evidence_summary, counter_evidence_summary, suggested_fix, draft_comment, fingerprint, merged_from_count, introduced_in_sha, first_seen_at, updated_at
`

type UpdateFindingDecisionStatusParams struct {
	DecisionStatus string `json:"decision_status"`
	UpdatedAt      string `json:"updated_at"`
	ID             string `json:"id"`
}

func (q *Queries) UpdateFindingDecisionStatus(ctx context.Context, arg UpdateFindingDecisionStatusParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, updateFindingDecisionStatus, arg.DecisionStatus, arg.UpdatedAt, arg.ID)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.CanonicalClaim,
		&i.Category,
		&i.Severity,
		&i.Confidence,
		&i.VerificationStatus,
		&i.DecisionStatus,
		&i.PrimaryPath,
		&i.PrimaryStartLine,
		&i.PrimaryEndLine,
		&i.EvidenceSummary,
		&i.CounterEvidenceSummary,
		&i.SuggestedFix,
		&i.DraftComment,
		&i.Fingerprint,
		&i.MergedFromCount,
		&i.IntroducedInSha,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFindingDraftComment = `-- name: UpdateFindingDraftComment :one
UPDATE findings
SET draft_comment = ?, updated_at = ?
WHERE id = ?
RETURNING id, review_session_id, canonical_claim, category, severity, confidence, verification_status, decision_status, primary_path, primary_start_line, primary_end_line, evidence_summary, counter_evidence_summary, suggested_fix, draft_comment, fingerprint, merged_from_count, introduced_in_sha, first_seen_at, updated_at
`

type UpdateFindingDraftCommentParams struct {
	DraftComment sql.NullString `json:"draft_comment"`
	UpdatedAt    string         `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateFindingDraftComment(ctx context.Context, arg UpdateFindingDraftCommentParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, updateFindingDraftComment, arg.DraftComment, arg.UpdatedAt, arg.ID)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.CanonicalClaim,
		&i.Category,
		&i.Severity,
		&i.Confidence,
		&i.VerificationStatus,
		&i.DecisionStatus,
		&i.PrimaryPath,
		&i.PrimaryStartLine,
		&i.PrimaryEndLine,
		&i.EvidenceSummary,
		&i.CounterEvidenceSummary,
		&i.SuggestedFix,
		&i.DraftComment,
		&i.Fingerprint,
		&i.MergedFromCount,
		&i.IntroducedInSha,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFindingVerificationEvidence = `-- name: UpdateFindingVerificationEvidence :one
UPDATE findings
SET
  verification_status = ?,
  evidence_summary = ?,
  counter_evidence_summary = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, review_session_id, canonical_claim, category, severity, confidence, verification_status, decision_status, primary_path, primary_start_line, primary_end_line, evidence_summary, counter_evidence_summary, suggested_fix, draft_comment, fingerprint, merged_from_count, introduced_in_sha, first_seen_at, updated_at
`

type UpdateFindingVerificationEvidenceParams struct {
	VerificationStatus     string         `json:"verification_status"`
	EvidenceSummary        sql.NullString `json:"evidence_summary"`
	CounterEvidenceSummary sql.NullString `json:"counter_evidence_summary"`
	UpdatedAt              string         `json:"updated_at"`
	ID                     string         `json:"id"`
}

func (q *Queries) UpdateFindingVerificationEvidence(ctx context.Context, arg UpdateFindingVerificationEvidenceParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, updateFindingVerificationEvidence,
		arg.VerificationStatus,
		arg.EvidenceSummary,
		arg.CounterEvidenceSummary,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.CanonicalClaim,
		&i.Category,
		&i.Severity,
		&i.Confidence,
		&i.VerificationStatus,
		&i.DecisionStatus,
		&i.PrimaryPath,
		&i.PrimaryStartLine,
		&i.PrimaryEndLine,
		&i.EvidenceSummary,
		&i.CounterEvidenceSummary,
		&i.SuggestedFix,
		&i.DraftComment,
		&i.Fingerprint,
		&i.MergedFromCount,
		&i.IntroducedInSha,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFindingVerificationStatus = `-- name: UpdateFindingVerificationStatus :one
UPDATE findings
SET verification_status = ?, updated_at = ?
WHERE id = ?
RETURNING id, review_session_id, canonical_claim, category, severity, confidence, verification_status, decision_status, primary_path, primary_start_line, primary_end_line, evidence_summary, counter_evidence_summary, suggested_fix, draft_comment, fingerprint, merged_from_count, introduced_in_sha, first_seen_at, updated_at
`

type UpdateFindingVerificationStatusParams struct {
	VerificationStatus string `json:"verification_status"`
	UpdatedAt          string `json:"updated_at"`
	ID                 string `json:"id"`
}

func (q *Queries) UpdateFindingVerificationStatus(ctx context.Context, arg UpdateFindingVerificationStatusParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, updateFindingVerificationStatus, arg.VerificationStatus, arg.UpdatedAt, arg.ID)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.CanonicalClaim,
		&i.Category,
		&i.Severity,
		&i.Confidence,
		&i.VerificationStatus,
		&i.DecisionStatus,
		&i.PrimaryPath,
		&i.PrimaryStartLine,
		&i.PrimaryEndLine,
		&i.EvidenceSummary,
		&i.CounterEvidenceSummary,
		&i.SuggestedFix,
		&i.DraftComment,
		&i.Fingerprint,
		&i.MergedFromCount,
		&i.IntroducedInSha,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}
