// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finding_threads.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createFindingThreadMessage = `-- name: CreateFindingThreadMessage :one
INSERT INTO finding_thread_messages (
  id,
  thread_id,
  role,
  agent_config_id,
  content,
  evidence_refs_json,
  artifact_id,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, thread_id, role, agent_config_id, content, evidence_refs_json, artifact_id, created_at
`

type CreateFindingThreadMessageParams struct {
	ID               string         `json:"id"`
	ThreadID         string         `json:"thread_id"`
	Role             string         `json:"role"`
	AgentConfigID    sql.NullString `json:"agent_config_id"`
	Content          string         `json:"content"`
	EvidenceRefsJson string         `json:"evidence_refs_json"`
	ArtifactID       sql.NullString `json:"artifact_id"`
	CreatedAt        string         `json:"created_at"`
}

func (q *Queries) CreateFindingThreadMessage(ctx context.Context, arg CreateFindingThreadMessageParams) (FindingThreadMessage, error) {
	row := q.db.QueryRowContext(ctx, createFindingThreadMessage,
		arg.ID,
		arg.ThreadID,
		arg.Role,
		arg.AgentConfigID,
		arg.Content,
		arg.EvidenceRefsJson,
		arg.ArtifactID,
		arg.CreatedAt,
	)
	var i FindingThreadMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Role,
		&i.AgentConfigID,
		&i.Content,
		&i.EvidenceRefsJson,
		&i.ArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const getFindingThread = `-- name: GetFindingThread :one
SELECT id, finding_id, review_session_id, title, created_at, updated_at
FROM finding_threads
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetFindingThread(ctx context.Context, id string) (FindingThread, error) {
	row := q.db.QueryRowContext(ctx, getFindingThread, id)
	var i FindingThread
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ReviewSessionID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFindingThreadByFinding = `-- name: GetFindingThreadByFinding :one
SELECT id, finding_id, review_session_id, title, created_at, updated_at
FROM finding_threads
WHERE finding_id = ?
LIMIT 1
`

func (q *Queries) GetFindingThreadByFinding(ctx context.Context, findingID string) (FindingThread, error) {
	row := q.db.QueryRowContext(ctx, getFindingThreadByFinding, findingID)
	var i FindingThread
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ReviewSessionID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFindingThreadMessage = `-- name: GetFindingThreadMessage :one
SELECT id, thread_id, role, agent_config_id, content, evidence_refs_json, artifact_id, created_at
FROM finding_thread_messages
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetFindingThreadMessage(ctx context.Context, id string) (FindingThreadMessage, error) {
	row := q.db.QueryRowContext(ctx, getFindingThreadMessage, id)
	var i FindingThreadMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Role,
		&i.AgentConfigID,
		&i.Content,
		&i.EvidenceRefsJson,
		&i.ArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const listFindingThreadMessages = `-- name: ListFindingThreadMessages :many
SELECT id, thread_id, role, agent_config_id, content, evidence_refs_json, artifact_id, created_at
FROM finding_thread_messages
WHERE thread_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListFindingThreadMessages(ctx context.Context, threadID string) ([]FindingThreadMessage, error) {
	rows, err := q.db.QueryContext(ctx, listFindingThreadMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingThreadMessage{}
	for rows.Next() {
		var i FindingThreadMessage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Role,
			&i.AgentConfigID,
			&i.Content,
			&i.EvidenceRefsJson,
			&i.ArtifactID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingThreadsBySession = `-- name: ListFindingThreadsBySession :many
SELECT id, finding_id, review_session_id, title, created_at, updated_at
FROM finding_threads
WHERE review_session_id = ?
ORDER BY updated_at DESC, id ASC
`

func (q *Queries) ListFindingThreadsBySession(ctx context.Context, reviewSessionID string) ([]FindingThread, error) {
	rows, err := q.db.QueryContext(ctx, listFindingThreadsBySession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingThread{}
	for rows.Next() {
		var i FindingThread
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.ReviewSessionID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFindingThread = `-- name: UpdateFindingThread :one
UPDATE finding_threads
SET title = ?, updated_at = ?
WHERE id = ?
RETURNING id, finding_id, review_session_id, title, created_at, updated_at
`

type UpdateFindingThreadParams struct {
	Title     string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateFindingThread(ctx context.Context, arg UpdateFindingThreadParams) (FindingThread, error) {
	row := q.db.QueryRowContext(ctx, updateFindingThread, arg.Title, arg.UpdatedAt, arg.ID)
	var i FindingThread
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ReviewSessionID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFindingThreadByFinding = `-- name: UpsertFindingThreadByFinding :one
INSERT INTO finding_threads (
  id,
  finding_id,
  review_session_id,
  title,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON CONFLICT(finding_id) DO UPDATE SET
  updated_at = finding_threads.updated_at
RETURNING id, finding_id, review_session_id, title, created_at, updated_at
`

type UpsertFindingThreadByFindingParams struct {
	ID              string `json:"id"`
	FindingID       string `json:"finding_id"`
	ReviewSessionID string `json:"review_session_id"`
	Title           string `json:"title"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) UpsertFindingThreadByFinding(ctx context.Context, arg UpsertFindingThreadByFindingParams) (FindingThread, error) {
	row := q.db.QueryRowContext(ctx, upsertFindingThreadByFinding,
		arg.ID,
		arg.FindingID,
		arg.ReviewSessionID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FindingThread
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ReviewSessionID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
