// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_publications.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createGitHubPublication = `-- name: CreateGitHubPublication :one
INSERT INTO github_publications (
  id,
  review_session_id,
  publish_draft_id,
  github_review_id,
  github_comment_ids_json,
  status,
  error_message,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, review_session_id, publish_draft_id, github_review_id, github_comment_ids_json, status, error_message, created_at
`

type CreateGitHubPublicationParams struct {
	ID                   string         `json:"id"`
	ReviewSessionID      string         `json:"review_session_id"`
	PublishDraftID       sql.NullString `json:"publish_draft_id"`
	GithubReviewID       sql.NullString `json:"github_review_id"`
	GithubCommentIdsJson string         `json:"github_comment_ids_json"`
	Status               string         `json:"status"`
	ErrorMessage         sql.NullString `json:"error_message"`
	CreatedAt            string         `json:"created_at"`
}

func (q *Queries) CreateGitHubPublication(ctx context.Context, arg CreateGitHubPublicationParams) (GithubPublication, error) {
	row := q.db.QueryRowContext(ctx, createGitHubPublication,
		arg.ID,
		arg.ReviewSessionID,
		arg.PublishDraftID,
		arg.GithubReviewID,
		arg.GithubCommentIdsJson,
		arg.Status,
		arg.ErrorMessage,
		arg.CreatedAt,
	)
	var i GithubPublication
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.PublishDraftID,
		&i.GithubReviewID,
		&i.GithubCommentIdsJson,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getGitHubPublication = `-- name: GetGitHubPublication :one
SELECT id, review_session_id, publish_draft_id, github_review_id, github_comment_ids_json, status, error_message, created_at
FROM github_publications
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetGitHubPublication(ctx context.Context, id string) (GithubPublication, error) {
	row := q.db.QueryRowContext(ctx, getGitHubPublication, id)
	var i GithubPublication
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.PublishDraftID,
		&i.GithubReviewID,
		&i.GithubCommentIdsJson,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listGitHubPublicationsBySession = `-- name: ListGitHubPublicationsBySession :many
SELECT id, review_session_id, publish_draft_id, github_review_id, github_comment_ids_json, status, error_message, created_at
FROM github_publications
WHERE review_session_id = ?
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListGitHubPublicationsBySession(ctx context.Context, reviewSessionID string) ([]GithubPublication, error) {
	rows, err := q.db.QueryContext(ctx, listGitHubPublicationsBySession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubPublication{}
	for rows.Next() {
		var i GithubPublication
		if err := rows.Scan(
			&i.ID,
			&i.ReviewSessionID,
			&i.PublishDraftID,
			&i.GithubReviewID,
			&i.GithubCommentIdsJson,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
