// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type AgentConfig struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Role             string         `json:"role"`
	AdapterKind      string         `json:"adapter_kind"`
	Command          sql.NullString `json:"command"`
	ArgsJson         string         `json:"args_json"`
	CwdMode          string         `json:"cwd_mode"`
	EnvAllowlistJson string         `json:"env_allowlist_json"`
	OutputMode       string         `json:"output_mode"`
	ModelLabel       sql.NullString `json:"model_label"`
	ReasoningLabel   sql.NullString `json:"reasoning_label"`
	CapabilitiesJson string         `json:"capabilities_json"`
	SettingsJson     string         `json:"settings_json"`
	Enabled          int64          `json:"enabled"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type AgentRun struct {
	ID                     string         `json:"id"`
	ReviewSessionID        string         `json:"review_session_id"`
	AgentConfigID          string         `json:"agent_config_id"`
	ContextBundleID        sql.NullString `json:"context_bundle_id"`
	Status                 string         `json:"status"`
	Role                   string         `json:"role"`
	StartedAt              sql.NullString `json:"started_at"`
	CompletedAt            sql.NullString `json:"completed_at"`
	DurationMs             sql.NullInt64  `json:"duration_ms"`
	ExitCode               sql.NullInt64  `json:"exit_code"`
	StdoutArtifactID       sql.NullString `json:"stdout_artifact_id"`
	StderrArtifactID       sql.NullString `json:"stderr_artifact_id"`
	ParsedOutputArtifactID sql.NullString `json:"parsed_output_artifact_id"`
	ErrorCode              sql.NullString `json:"error_code"`
	ErrorMessage           sql.NullString `json:"error_message"`
	MetadataJson           string         `json:"metadata_json"`
}

type Artifact struct {
	ID              string         `json:"id"`
	WorkspaceID     string         `json:"workspace_id"`
	ReviewSessionID sql.NullString `json:"review_session_id"`
	Kind            string         `json:"kind"`
	RelativePath    string         `json:"relative_path"`
	ContentType     string         `json:"content_type"`
	SizeBytes       int64          `json:"size_bytes"`
	Sha256          sql.NullString `json:"sha256"`
	MetadataJson    string         `json:"metadata_json"`
	CreatedAt       string         `json:"created_at"`
}

type CallPath struct {
	ID              string         `json:"id"`
	EvidenceGraphID string         `json:"evidence_graph_id"`
	Label           sql.NullString `json:"label"`
	Confidence      float64        `json:"confidence"`
	CreatedAt       string         `json:"created_at"`
}

type CallPathStep struct {
	ID         string         `json:"id"`
	CallPathID string         `json:"call_path_id"`
	StepIndex  int64          `json:"step_index"`
	NodeID     sql.NullString `json:"node_id"`
	Path       sql.NullString `json:"path"`
	StartLine  sql.NullInt64  `json:"start_line"`
	EndLine    sql.NullInt64  `json:"end_line"`
	Label      string         `json:"label"`
}

type ChangedFile struct {
	ID              string         `json:"id"`
	SnapshotID      string         `json:"snapshot_id"`
	Path            string         `json:"path"`
	OldPath         sql.NullString `json:"old_path"`
	Status          string         `json:"status"`
	Additions       int64          `json:"additions"`
	Deletions       int64          `json:"deletions"`
	IsBinary        int64          `json:"is_binary"`
	IsGenerated     int64          `json:"is_generated"`
	IsExcluded      int64          `json:"is_excluded"`
	LineRangesJson  string         `json:"line_ranges_json"`
	PatchArtifactID sql.NullString `json:"patch_artifact_id"`
	CreatedAt       string         `json:"created_at"`
}

type ContextBundle struct {
	ID              string         `json:"id"`
	ReviewSessionID string         `json:"review_session_id"`
	AgentConfigID   sql.NullString `json:"agent_config_id"`
	Scope           string         `json:"scope"`
	TokenEstimate   int64          `json:"token_estimate"`
	ItemCount       int64          `json:"item_count"`
	ArtifactID      sql.NullString `json:"artifact_id"`
	PolicyJson      string         `json:"policy_json"`
	CreatedAt       string         `json:"created_at"`
}

type ContextItem struct {
	ID                string         `json:"id"`
	ContextBundleID   string         `json:"context_bundle_id"`
	Kind              string         `json:"kind"`
	Path              sql.NullString `json:"path"`
	StartLine         sql.NullInt64  `json:"start_line"`
	EndLine           sql.NullInt64  `json:"end_line"`
	Title             sql.NullString `json:"title"`
	ContentArtifactID sql.NullString `json:"content_artifact_id"`
	TokenEstimate     int64          `json:"token_estimate"`
	MetadataJson      string         `json:"metadata_json"`
}

type CredentialRef struct {
	ID              string `json:"id"`
	Kind            string `json:"kind"`
	DisplayName     string `json:"display_name"`
	StorageProvider string `json:"storage_provider"`
	StorageKey      string `json:"storage_key"`
	MetadataJson    string `json:"metadata_json"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type Event struct {
	ID              string         `json:"id"`
	ReviewSessionID sql.NullString `json:"review_session_id"`
	AgentRunID      sql.NullString `json:"agent_run_id"`
	Type            string         `json:"type"`
	Level           string         `json:"level"`
	Sequence        int64          `json:"sequence"`
	PayloadJson     string         `json:"payload_json"`
	ArtifactID      sql.NullString `json:"artifact_id"`
	CreatedAt       string         `json:"created_at"`
}

type EvidenceEdge struct {
	ID              string         `json:"id"`
	EvidenceGraphID string         `json:"evidence_graph_id"`
	SourceNodeID    string         `json:"source_node_id"`
	TargetNodeID    string         `json:"target_node_id"`
	Kind            string         `json:"kind"`
	Status          string         `json:"status"`
	Label           sql.NullString `json:"label"`
	Confidence      float64        `json:"confidence"`
	MetadataJson    string         `json:"metadata_json"`
}

type EvidenceGraph struct {
	ID              string         `json:"id"`
	FindingID       string         `json:"finding_id"`
	ReviewSessionID string         `json:"review_session_id"`
	Status          string         `json:"status"`
	LayoutJson      string         `json:"layout_json"`
	Summary         sql.NullString `json:"summary"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type EvidenceItem struct {
	ID           string         `json:"id"`
	FindingID    string         `json:"finding_id"`
	Kind         string         `json:"kind"`
	Title        string         `json:"title"`
	Summary      string         `json:"summary"`
	Path         sql.NullString `json:"path"`
	StartLine    sql.NullInt64  `json:"start_line"`
	EndLine      sql.NullInt64  `json:"end_line"`
	ArtifactID   sql.NullString `json:"artifact_id"`
	Confidence   float64        `json:"confidence"`
	MetadataJson string         `json:"metadata_json"`
	CreatedAt    string         `json:"created_at"`
}

type EvidenceNode struct {
	ID              string         `json:"id"`
	EvidenceGraphID string         `json:"evidence_graph_id"`
	Kind            string         `json:"kind"`
	Label           string         `json:"label"`
	Path            sql.NullString `json:"path"`
	Symbol          sql.NullString `json:"symbol"`
	StartLine       sql.NullInt64  `json:"start_line"`
	EndLine         sql.NullInt64  `json:"end_line"`
	EvidenceItemID  sql.NullString `json:"evidence_item_id"`
	Confidence      float64        `json:"confidence"`
	MetadataJson    string         `json:"metadata_json"`
}

type EvidenceSearch struct {
	EvidenceItemID string `json:"evidence_item_id"`
	Title          string `json:"title"`
	Summary        string `json:"summary"`
	Path           string `json:"path"`
}

type Finding struct {
	ID                     string         `json:"id"`
	ReviewSessionID        string         `json:"review_session_id"`
	CanonicalClaim         string         `json:"canonical_claim"`
	Category               string         `json:"category"`
	Severity               string         `json:"severity"`
	Confidence             float64        `json:"confidence"`
	VerificationStatus     string         `json:"verification_status"`
	DecisionStatus         string         `json:"decision_status"`
	PrimaryPath            sql.NullString `json:"primary_path"`
	PrimaryStartLine       sql.NullInt64  `json:"primary_start_line"`
	PrimaryEndLine         sql.NullInt64  `json:"primary_end_line"`
	EvidenceSummary        sql.NullString `json:"evidence_summary"`
	CounterEvidenceSummary sql.NullString `json:"counter_evidence_summary"`
	SuggestedFix           sql.NullString `json:"suggested_fix"`
	DraftComment           sql.NullString `json:"draft_comment"`
	Fingerprint            string         `json:"fingerprint"`
	MergedFromCount        int64          `json:"merged_from_count"`
	IntroducedInSha        sql.NullString `json:"introduced_in_sha"`
	FirstSeenAt            string         `json:"first_seen_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type FindingCandidate struct {
	ID               string         `json:"id"`
	ReviewSessionID  string         `json:"review_session_id"`
	AgentRunID       string         `json:"agent_run_id"`
	RawArtifactID    sql.NullString `json:"raw_artifact_id"`
	Category         string         `json:"category"`
	Severity         string         `json:"severity"`
	Confidence       float64        `json:"confidence"`
	Claim            string         `json:"claim"`
	PrimaryPath      sql.NullString `json:"primary_path"`
	PrimaryStartLine sql.NullInt64  `json:"primary_start_line"`
	PrimaryEndLine   sql.NullInt64  `json:"primary_end_line"`
	LocationsJson    string         `json:"locations_json"`
	EvidenceJson     string         `json:"evidence_json"`
	SuggestedFix     sql.NullString `json:"suggested_fix"`
	DraftComment     sql.NullString `json:"draft_comment"`
	Fingerprint      sql.NullString `json:"fingerprint"`
	CreatedAt        string         `json:"created_at"`
}

type FindingCandidateLink struct {
	FindingID          string `json:"finding_id"`
	FindingCandidateID string `json:"finding_candidate_id"`
	Relation           string `json:"relation"`
}

type FindingSearch struct {
	FindingID       string `json:"finding_id"`
	Claim           string `json:"claim"`
	EvidenceSummary string `json:"evidence_summary"`
	SuggestedFix    string `json:"suggested_fix"`
	DraftComment    string `json:"draft_comment"`
}

type FindingThread struct {
	ID              string `json:"id"`
	FindingID       string `json:"finding_id"`
	ReviewSessionID string `json:"review_session_id"`
	Title           string `json:"title"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type FindingThreadMessage struct {
	ID               string         `json:"id"`
	ThreadID         string         `json:"thread_id"`
	Role             string         `json:"role"`
	AgentConfigID    sql.NullString `json:"agent_config_id"`
	Content          string         `json:"content"`
	EvidenceRefsJson string         `json:"evidence_refs_json"`
	ArtifactID       sql.NullString `json:"artifact_id"`
	CreatedAt        string         `json:"created_at"`
}

type HumanDecision struct {
	ID              string         `json:"id"`
	FindingID       string         `json:"finding_id"`
	ReviewSessionID string         `json:"review_session_id"`
	Decision        string         `json:"decision"`
	Reason          sql.NullString `json:"reason"`
	MetadataJson    string         `json:"metadata_json"`
	CreatedAt       string         `json:"created_at"`
}

type PullRequestSnapshot struct {
	ID             string         `json:"id"`
	RepositoryID   string         `json:"repository_id"`
	SourceType     string         `json:"source_type"`
	Provider       sql.NullString `json:"provider"`
	Owner          sql.NullString `json:"owner"`
	Repo           sql.NullString `json:"repo"`
	PrNumber       sql.NullInt64  `json:"pr_number"`
	PrTitle        sql.NullString `json:"pr_title"`
	PrUrl          sql.NullString `json:"pr_url"`
	BaseRef        sql.NullString `json:"base_ref"`
	HeadRef        sql.NullString `json:"head_ref"`
	BaseSha        sql.NullString `json:"base_sha"`
	HeadSha        sql.NullString `json:"head_sha"`
	DiffArtifactID sql.NullString `json:"diff_artifact_id"`
	MetadataJson   string         `json:"metadata_json"`
	CreatedAt      string         `json:"created_at"`
}

type Repository struct {
	ID            string         `json:"id"`
	WorkspaceID   string         `json:"workspace_id"`
	Name          string         `json:"name"`
	Owner         sql.NullString `json:"owner"`
	RemoteUrl     sql.NullString `json:"remote_url"`
	LocalPath     string         `json:"local_path"`
	DefaultBranch sql.NullString `json:"default_branch"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type ReviewRule struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Scope       string `json:"scope"`
	RuleType    string `json:"rule_type"`
	Content     string `json:"content"`
	Enabled     int64  `json:"enabled"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type ReviewSession struct {
	ID                  string         `json:"id"`
	WorkspaceID         string         `json:"workspace_id"`
	RepositoryID        string         `json:"repository_id"`
	SnapshotID          string         `json:"snapshot_id"`
	Title               string         `json:"title"`
	Status              string         `json:"status"`
	ReviewDepth         string         `json:"review_depth"`
	FocusPrompt         sql.NullString `json:"focus_prompt"`
	Preset              sql.NullString `json:"preset"`
	RuntimeLimitSeconds int64          `json:"runtime_limit_seconds"`
	ContextPolicyJson   string         `json:"context_policy_json"`
	StartedAt           sql.NullString `json:"started_at"`
	CompletedAt         sql.NullString `json:"completed_at"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

type ReviewSessionAgent struct {
	ID                   string `json:"id"`
	ReviewSessionID      string `json:"review_session_id"`
	AgentConfigID        string `json:"agent_config_id"`
	Role                 string `json:"role"`
	RunOrder             int64  `json:"run_order"`
	Enabled              int64  `json:"enabled"`
	SettingsOverrideJson string `json:"settings_override_json"`
}

type Workspace struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	RootPath      string         `json:"root_path"`
	DefaultRepoID sql.NullString `json:"default_repo_id"`
	SettingsJson  string         `json:"settings_json"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}
