// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type Workspace struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	RootPath      string         `json:"root_path"`
	DefaultRepoID sql.NullString `json:"default_repo_id"`
	SettingsJson  string         `json:"settings_json"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}
