// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publish_drafts.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createPublishDraft = `-- name: CreatePublishDraft :one
INSERT INTO publish_drafts (
  id,
  review_session_id,
  provider,
  status,
  review_event,
  body,
  comments_json,
  artifact_id,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, review_session_id, provider, status, review_event, body, comments_json, artifact_id, created_at, updated_at
`

type CreatePublishDraftParams struct {
	ID              string         `json:"id"`
	ReviewSessionID string         `json:"review_session_id"`
	Provider        string         `json:"provider"`
	Status          string         `json:"status"`
	ReviewEvent     sql.NullString `json:"review_event"`
	Body            sql.NullString `json:"body"`
	CommentsJson    string         `json:"comments_json"`
	ArtifactID      sql.NullString `json:"artifact_id"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

func (q *Queries) CreatePublishDraft(ctx context.Context, arg CreatePublishDraftParams) (PublishDraft, error) {
	row := q.db.QueryRowContext(ctx, createPublishDraft,
		arg.ID,
		arg.ReviewSessionID,
		arg.Provider,
		arg.Status,
		arg.ReviewEvent,
		arg.Body,
		arg.CommentsJson,
		arg.ArtifactID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PublishDraft
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.Provider,
		&i.Status,
		&i.ReviewEvent,
		&i.Body,
		&i.CommentsJson,
		&i.ArtifactID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishDraft = `-- name: GetPublishDraft :one
SELECT id, review_session_id, provider, status, review_event, body, comments_json, artifact_id, created_at, updated_at
FROM publish_drafts
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPublishDraft(ctx context.Context, id string) (PublishDraft, error) {
	row := q.db.QueryRowContext(ctx, getPublishDraft, id)
	var i PublishDraft
	err := row.Scan(
		&i.ID,
		&i.ReviewSessionID,
		&i.Provider,
		&i.Status,
		&i.ReviewEvent,
		&i.Body,
		&i.CommentsJson,
		&i.ArtifactID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishDraftsBySession = `-- name: ListPublishDraftsBySession :many
SELECT id, review_session_id, provider, status, review_event, body, comments_json, artifact_id, created_at, updated_at
FROM publish_drafts
WHERE review_session_id = ?
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListPublishDraftsBySession(ctx context.Context, reviewSessionID string) ([]PublishDraft, error) {
	rows, err := q.db.QueryContext(ctx, listPublishDraftsBySession, reviewSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublishDraft{}
	for rows.Next() {
		var i PublishDraft
		if err := rows.Scan(
			&i.ID,
			&i.ReviewSessionID,
			&i.Provider,
			&i.Status,
			&i.ReviewEvent,
			&i.Body,
			&i.CommentsJson,
			&i.ArtifactID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
