// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAgentConfig(ctx context.Context, arg CreateAgentConfigParams) (AgentConfig, error)
	CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error)
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	CreateCallPath(ctx context.Context, arg CreateCallPathParams) (CallPath, error)
	CreateCallPathStep(ctx context.Context, arg CreateCallPathStepParams) (CallPathStep, error)
	CreateChangedFile(ctx context.Context, arg CreateChangedFileParams) (ChangedFile, error)
	CreateContextBundle(ctx context.Context, arg CreateContextBundleParams) (ContextBundle, error)
	CreateContextItem(ctx context.Context, arg CreateContextItemParams) (ContextItem, error)
	CreateCopyPacket(ctx context.Context, arg CreateCopyPacketParams) (CopyPacket, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateEvidenceEdge(ctx context.Context, arg CreateEvidenceEdgeParams) (EvidenceEdge, error)
	CreateEvidenceGraph(ctx context.Context, arg CreateEvidenceGraphParams) (EvidenceGraph, error)
	CreateEvidenceItem(ctx context.Context, arg CreateEvidenceItemParams) (EvidenceItem, error)
	CreateEvidenceNode(ctx context.Context, arg CreateEvidenceNodeParams) (EvidenceNode, error)
	CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error)
	CreateFindingCandidate(ctx context.Context, arg CreateFindingCandidateParams) (FindingCandidate, error)
	CreateFindingThreadMessage(ctx context.Context, arg CreateFindingThreadMessageParams) (FindingThreadMessage, error)
	CreateGitHubPublication(ctx context.Context, arg CreateGitHubPublicationParams) (GithubPublication, error)
	CreateHumanDecision(ctx context.Context, arg CreateHumanDecisionParams) (HumanDecision, error)
	CreatePublishDraft(ctx context.Context, arg CreatePublishDraftParams) (PublishDraft, error)
	CreatePullRequestSnapshot(ctx context.Context, arg CreatePullRequestSnapshotParams) (PullRequestSnapshot, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateReviewRule(ctx context.Context, arg CreateReviewRuleParams) (ReviewRule, error)
	CreateReviewSession(ctx context.Context, arg CreateReviewSessionParams) (ReviewSession, error)
	CreateReviewSessionAgent(ctx context.Context, arg CreateReviewSessionAgentParams) (ReviewSessionAgent, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteAgentConfig(ctx context.Context, id string) error
	DeleteArtifact(ctx context.Context, id string) error
	DeleteCallPath(ctx context.Context, id string) error
	DeleteContextBundle(ctx context.Context, id string) error
	DeleteContextItem(ctx context.Context, id string) error
	DeleteCredentialRef(ctx context.Context, id string) error
	DeleteEvidenceEdge(ctx context.Context, id string) error
	DeleteEvidenceGraph(ctx context.Context, id string) error
	DeleteEvidenceItem(ctx context.Context, id string) error
	DeleteEvidenceNode(ctx context.Context, id string) error
	DeleteEvidenceSearch(ctx context.Context, evidenceItemID string) error
	DeleteFinding(ctx context.Context, id string) error
	DeleteFindingCandidate(ctx context.Context, id string) error
	DeleteFindingSearch(ctx context.Context, findingID string) error
	DeletePullRequestSnapshot(ctx context.Context, id string) error
	DeleteRepository(ctx context.Context, id string) error
	DeleteReviewRule(ctx context.Context, id string) error
	DeleteReviewSession(ctx context.Context, id string) error
	DeleteWorkspace(ctx context.Context, id string) error
	GetAgentConfig(ctx context.Context, id string) (AgentConfig, error)
	GetAgentRun(ctx context.Context, id string) (AgentRun, error)
	GetArtifact(ctx context.Context, id string) (Artifact, error)
	GetChangedFile(ctx context.Context, id string) (ChangedFile, error)
	GetChangedFileByPath(ctx context.Context, arg GetChangedFileByPathParams) (ChangedFile, error)
	GetContextBundle(ctx context.Context, id string) (ContextBundle, error)
	GetContextItem(ctx context.Context, id string) (ContextItem, error)
	GetCopyPacket(ctx context.Context, id string) (CopyPacket, error)
	GetCredentialRef(ctx context.Context, id string) (CredentialRef, error)
	GetEvent(ctx context.Context, id string) (Event, error)
	GetEvidenceGraph(ctx context.Context, id string) (EvidenceGraph, error)
	GetEvidenceGraphByFinding(ctx context.Context, findingID string) (EvidenceGraph, error)
	GetEvidenceItem(ctx context.Context, id string) (EvidenceItem, error)
	GetEvidenceNode(ctx context.Context, id string) (EvidenceNode, error)
	GetFinding(ctx context.Context, id string) (Finding, error)
	GetFindingCandidate(ctx context.Context, id string) (FindingCandidate, error)
	GetFindingThread(ctx context.Context, id string) (FindingThread, error)
	GetFindingThreadByFinding(ctx context.Context, findingID string) (FindingThread, error)
	GetFindingThreadMessage(ctx context.Context, id string) (FindingThreadMessage, error)
	GetGitHubPublication(ctx context.Context, id string) (GithubPublication, error)
	GetLatestCredentialRefByKind(ctx context.Context, kind string) (CredentialRef, error)
	GetPublishDraft(ctx context.Context, id string) (PublishDraft, error)
	GetPullRequestSnapshot(ctx context.Context, id string) (PullRequestSnapshot, error)
	GetRepository(ctx context.Context, id string) (Repository, error)
	GetRepositoryByLocalPath(ctx context.Context, arg GetRepositoryByLocalPathParams) (Repository, error)
	GetReviewRule(ctx context.Context, id string) (ReviewRule, error)
	GetReviewSession(ctx context.Context, id string) (ReviewSession, error)
	GetWorkspace(ctx context.Context, id string) (Workspace, error)
	GetWorkspaceByRootPath(ctx context.Context, rootPath string) (Workspace, error)
	InsertEvidenceSearch(ctx context.Context, arg InsertEvidenceSearchParams) error
	InsertFindingSearch(ctx context.Context, arg InsertFindingSearchParams) error
	LinkFindingCandidate(ctx context.Context, arg LinkFindingCandidateParams) error
	ListAgentConfigs(ctx context.Context) ([]AgentConfig, error)
	ListAgentRunsBySession(ctx context.Context, reviewSessionID string) ([]AgentRun, error)
	ListArtifactsByReviewSession(ctx context.Context, reviewSessionID sql.NullString) ([]Artifact, error)
	ListArtifactsByWorkspace(ctx context.Context, workspaceID string) ([]Artifact, error)
	ListCallPathStepsByCallPath(ctx context.Context, callPathID string) ([]CallPathStep, error)
	ListCallPathsByGraph(ctx context.Context, evidenceGraphID string) ([]CallPath, error)
	ListChangedFilesBySnapshot(ctx context.Context, snapshotID string) ([]ChangedFile, error)
	ListContextBundlesBySession(ctx context.Context, reviewSessionID string) ([]ContextBundle, error)
	ListContextItemsByBundle(ctx context.Context, contextBundleID string) ([]ContextItem, error)
	ListCopyPacketsBySession(ctx context.Context, reviewSessionID string) ([]CopyPacket, error)
	ListEnabledReviewRulesByWorkspace(ctx context.Context, workspaceID string) ([]ReviewRule, error)
	ListEventsByReviewSession(ctx context.Context, reviewSessionID sql.NullString) ([]Event, error)
	ListEvidenceEdgesByGraph(ctx context.Context, evidenceGraphID string) ([]EvidenceEdge, error)
	ListEvidenceItemsByFinding(ctx context.Context, findingID string) ([]EvidenceItem, error)
	ListEvidenceItemsBySession(ctx context.Context, reviewSessionID string) ([]EvidenceItem, error)
	ListEvidenceNodesByGraph(ctx context.Context, evidenceGraphID string) ([]EvidenceNode, error)
	ListFindingCandidateLinks(ctx context.Context, findingID string) ([]FindingCandidateLink, error)
	ListFindingCandidatesBySession(ctx context.Context, reviewSessionID string) ([]FindingCandidate, error)
	ListFindingThreadMessages(ctx context.Context, threadID string) ([]FindingThreadMessage, error)
	ListFindingThreadsBySession(ctx context.Context, reviewSessionID string) ([]FindingThread, error)
	ListFindingsBySession(ctx context.Context, reviewSessionID string) ([]Finding, error)
	ListGitHubPublicationsBySession(ctx context.Context, reviewSessionID string) ([]GithubPublication, error)
	ListHumanDecisionsByFinding(ctx context.Context, findingID string) ([]HumanDecision, error)
	ListHumanDecisionsBySession(ctx context.Context, reviewSessionID string) ([]HumanDecision, error)
	ListInterruptedAgentRuns(ctx context.Context) ([]AgentRun, error)
	ListInterruptedReviewSessions(ctx context.Context) ([]ReviewSession, error)
	ListPublishDraftsBySession(ctx context.Context, reviewSessionID string) ([]PublishDraft, error)
	ListPullRequestSnapshotsByRepository(ctx context.Context, repositoryID string) ([]PullRequestSnapshot, error)
	ListRepositoriesByWorkspace(ctx context.Context, workspaceID string) ([]Repository, error)
	ListReviewRulesByWorkspace(ctx context.Context, workspaceID string) ([]ReviewRule, error)
	ListReviewSessionAgents(ctx context.Context, reviewSessionID string) ([]ReviewSessionAgent, error)
	ListReviewSessionsByWorkspace(ctx context.Context, workspaceID string) ([]ReviewSession, error)
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	MarkCopyPacketCopied(ctx context.Context, arg MarkCopyPacketCopiedParams) (CopyPacket, error)
	NextEventSequence(ctx context.Context, reviewSessionID sql.NullString) (int64, error)
	SearchEvidence(ctx context.Context, arg SearchEvidenceParams) ([]string, error)
	SearchFindings(ctx context.Context, arg SearchFindingsParams) ([]string, error)
	SetReviewRuleEnabled(ctx context.Context, arg SetReviewRuleEnabledParams) (ReviewRule, error)
	UpdateAgentConfig(ctx context.Context, arg UpdateAgentConfigParams) (AgentConfig, error)
	UpdateAgentRunStatus(ctx context.Context, arg UpdateAgentRunStatusParams) (AgentRun, error)
	UpdateCallPath(ctx context.Context, arg UpdateCallPathParams) (CallPath, error)
	UpdateChangedFileExclusion(ctx context.Context, arg UpdateChangedFileExclusionParams) (ChangedFile, error)
	UpdateContextBundleArtifact(ctx context.Context, arg UpdateContextBundleArtifactParams) (ContextBundle, error)
	UpdateEvidenceEdge(ctx context.Context, arg UpdateEvidenceEdgeParams) (EvidenceEdge, error)
	UpdateEvidenceGraph(ctx context.Context, arg UpdateEvidenceGraphParams) (EvidenceGraph, error)
	UpdateEvidenceItem(ctx context.Context, arg UpdateEvidenceItemParams) (EvidenceItem, error)
	UpdateEvidenceNode(ctx context.Context, arg UpdateEvidenceNodeParams) (EvidenceNode, error)
	UpdateFinding(ctx context.Context, arg UpdateFindingParams) (Finding, error)
	UpdateFindingDecisionStatus(ctx context.Context, arg UpdateFindingDecisionStatusParams) (Finding, error)
	UpdateFindingDraftComment(ctx context.Context, arg UpdateFindingDraftCommentParams) (Finding, error)
	UpdateFindingThread(ctx context.Context, arg UpdateFindingThreadParams) (FindingThread, error)
	UpdateFindingVerificationEvidence(ctx context.Context, arg UpdateFindingVerificationEvidenceParams) (Finding, error)
	UpdateFindingVerificationStatus(ctx context.Context, arg UpdateFindingVerificationStatusParams) (Finding, error)
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error)
	UpdateReviewRule(ctx context.Context, arg UpdateReviewRuleParams) (ReviewRule, error)
	UpdateReviewSession(ctx context.Context, arg UpdateReviewSessionParams) (ReviewSession, error)
	UpdateReviewSessionAgentEnabled(ctx context.Context, arg UpdateReviewSessionAgentEnabledParams) (ReviewSessionAgent, error)
	UpdateReviewSessionStatus(ctx context.Context, arg UpdateReviewSessionStatusParams) (ReviewSession, error)
	UpdateReviewSessionStatusIfCurrent(ctx context.Context, arg UpdateReviewSessionStatusIfCurrentParams) (ReviewSession, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpsertCredentialRef(ctx context.Context, arg UpsertCredentialRefParams) (CredentialRef, error)
	UpsertFindingThreadByFinding(ctx context.Context, arg UpsertFindingThreadByFindingParams) (FindingThread, error)
}

var _ Querier = (*Queries)(nil)
