// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (
  id,
  workspace_id,
  name,
  owner,
  remote_url,
  local_path,
  default_branch,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, workspace_id, name, owner, remote_url, local_path, default_branch, created_at, updated_at
`

type CreateRepositoryParams struct {
	ID            string         `json:"id"`
	WorkspaceID   string         `json:"workspace_id"`
	Name          string         `json:"name"`
	Owner         sql.NullString `json:"owner"`
	RemoteUrl     sql.NullString `json:"remote_url"`
	LocalPath     string         `json:"local_path"`
	DefaultBranch sql.NullString `json:"default_branch"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, createRepository,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Owner,
		arg.RemoteUrl,
		arg.LocalPath,
		arg.DefaultBranch,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Owner,
		&i.RemoteUrl,
		&i.LocalPath,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM repositories
WHERE id = ?
`

func (q *Queries) DeleteRepository(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRepository, id)
	return err
}

const getRepository = `-- name: GetRepository :one
SELECT id, workspace_id, name, owner, remote_url, local_path, default_branch, created_at, updated_at
FROM repositories
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetRepository(ctx context.Context, id string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Owner,
		&i.RemoteUrl,
		&i.LocalPath,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByLocalPath = `-- name: GetRepositoryByLocalPath :one
SELECT id, workspace_id, name, owner, remote_url, local_path, default_branch, created_at, updated_at
FROM repositories
WHERE workspace_id = ? AND local_path = ?
LIMIT 1
`

type GetRepositoryByLocalPathParams struct {
	WorkspaceID string `json:"workspace_id"`
	LocalPath   string `json:"local_path"`
}

func (q *Queries) GetRepositoryByLocalPath(ctx context.Context, arg GetRepositoryByLocalPathParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByLocalPath, arg.WorkspaceID, arg.LocalPath)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Owner,
		&i.RemoteUrl,
		&i.LocalPath,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositoriesByWorkspace = `-- name: ListRepositoriesByWorkspace :many
SELECT id, workspace_id, name, owner, remote_url, local_path, default_branch, created_at, updated_at
FROM repositories
WHERE workspace_id = ?
ORDER BY updated_at DESC, name ASC
`

func (q *Queries) ListRepositoriesByWorkspace(ctx context.Context, workspaceID string) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listRepositoriesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Owner,
			&i.RemoteUrl,
			&i.LocalPath,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepository = `-- name: UpdateRepository :one
UPDATE repositories
SET
  name = ?,
  owner = ?,
  remote_url = ?,
  default_branch = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, workspace_id, name, owner, remote_url, local_path, default_branch, created_at, updated_at
`

type UpdateRepositoryParams struct {
	Name          string         `json:"name"`
	Owner         sql.NullString `json:"owner"`
	RemoteUrl     sql.NullString `json:"remote_url"`
	DefaultBranch sql.NullString `json:"default_branch"`
	UpdatedAt     string         `json:"updated_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, updateRepository,
		arg.Name,
		arg.Owner,
		arg.RemoteUrl,
		arg.DefaultBranch,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Owner,
		&i.RemoteUrl,
		&i.LocalPath,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
