// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_rules.sql

package dbgen

import (
	"context"
)

const createReviewRule = `-- name: CreateReviewRule :one
INSERT INTO review_rules (
  id,
  workspace_id,
  scope,
  rule_type,
  content,
  enabled,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, workspace_id, scope, rule_type, content, enabled, created_at, updated_at
`

type CreateReviewRuleParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Scope       string `json:"scope"`
	RuleType    string `json:"rule_type"`
	Content     string `json:"content"`
	Enabled     int64  `json:"enabled"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreateReviewRule(ctx context.Context, arg CreateReviewRuleParams) (ReviewRule, error) {
	row := q.db.QueryRowContext(ctx, createReviewRule,
		arg.ID,
		arg.WorkspaceID,
		arg.Scope,
		arg.RuleType,
		arg.Content,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ReviewRule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Scope,
		&i.RuleType,
		&i.Content,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReviewRule = `-- name: DeleteReviewRule :exec
DELETE FROM review_rules
WHERE id = ?
`

func (q *Queries) DeleteReviewRule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteReviewRule, id)
	return err
}

const getReviewRule = `-- name: GetReviewRule :one
SELECT id, workspace_id, scope, rule_type, content, enabled, created_at, updated_at
FROM review_rules
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetReviewRule(ctx context.Context, id string) (ReviewRule, error) {
	row := q.db.QueryRowContext(ctx, getReviewRule, id)
	var i ReviewRule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Scope,
		&i.RuleType,
		&i.Content,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledReviewRulesByWorkspace = `-- name: ListEnabledReviewRulesByWorkspace :many
SELECT id, workspace_id, scope, rule_type, content, enabled, created_at, updated_at
FROM review_rules
WHERE workspace_id = ? AND enabled = 1
ORDER BY scope ASC, rule_type ASC, updated_at DESC, id ASC
`

func (q *Queries) ListEnabledReviewRulesByWorkspace(ctx context.Context, workspaceID string) ([]ReviewRule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledReviewRulesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRule{}
	for rows.Next() {
		var i ReviewRule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Scope,
			&i.RuleType,
			&i.Content,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewRulesByWorkspace = `-- name: ListReviewRulesByWorkspace :many
SELECT id, workspace_id, scope, rule_type, content, enabled, created_at, updated_at
FROM review_rules
WHERE workspace_id = ?
ORDER BY enabled DESC, scope ASC, rule_type ASC, updated_at DESC, id ASC
`

func (q *Queries) ListReviewRulesByWorkspace(ctx context.Context, workspaceID string) ([]ReviewRule, error) {
	rows, err := q.db.QueryContext(ctx, listReviewRulesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRule{}
	for rows.Next() {
		var i ReviewRule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Scope,
			&i.RuleType,
			&i.Content,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReviewRuleEnabled = `-- name: SetReviewRuleEnabled :one
UPDATE review_rules
SET enabled = ?, updated_at = ?
WHERE id = ?
RETURNING id, workspace_id, scope, rule_type, content, enabled, created_at, updated_at
`

type SetReviewRuleEnabledParams struct {
	Enabled   int64  `json:"enabled"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) SetReviewRuleEnabled(ctx context.Context, arg SetReviewRuleEnabledParams) (ReviewRule, error) {
	row := q.db.QueryRowContext(ctx, setReviewRuleEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	var i ReviewRule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Scope,
		&i.RuleType,
		&i.Content,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReviewRule = `-- name: UpdateReviewRule :one
UPDATE review_rules
SET
  scope = ?,
  rule_type = ?,
  content = ?,
  enabled = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, workspace_id, scope, rule_type, content, enabled, created_at, updated_at
`

type UpdateReviewRuleParams struct {
	Scope     string `json:"scope"`
	RuleType  string `json:"rule_type"`
	Content   string `json:"content"`
	Enabled   int64  `json:"enabled"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateReviewRule(ctx context.Context, arg UpdateReviewRuleParams) (ReviewRule, error) {
	row := q.db.QueryRowContext(ctx, updateReviewRule,
		arg.Scope,
		arg.RuleType,
		arg.Content,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ReviewRule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Scope,
		&i.RuleType,
		&i.Content,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
