// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_sessions.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createReviewSession = `-- name: CreateReviewSession :one
INSERT INTO review_sessions (
  id,
  workspace_id,
  repository_id,
  snapshot_id,
  title,
  status,
  review_depth,
  focus_prompt,
  preset,
  runtime_limit_seconds,
  context_policy_json,
  started_at,
  completed_at,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, workspace_id, repository_id, snapshot_id, title, status, review_depth, focus_prompt, preset, runtime_limit_seconds, context_policy_json, started_at, completed_at, created_at, updated_at
`

type CreateReviewSessionParams struct {
	ID                  string         `json:"id"`
	WorkspaceID         string         `json:"workspace_id"`
	RepositoryID        string         `json:"repository_id"`
	SnapshotID          string         `json:"snapshot_id"`
	Title               string         `json:"title"`
	Status              string         `json:"status"`
	ReviewDepth         string         `json:"review_depth"`
	FocusPrompt         sql.NullString `json:"focus_prompt"`
	Preset              sql.NullString `json:"preset"`
	RuntimeLimitSeconds int64          `json:"runtime_limit_seconds"`
	ContextPolicyJson   string         `json:"context_policy_json"`
	StartedAt           sql.NullString `json:"started_at"`
	CompletedAt         sql.NullString `json:"completed_at"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

func (q *Queries) CreateReviewSession(ctx context.Context, arg CreateReviewSessionParams) (ReviewSession, error) {
	row := q.db.QueryRowContext(ctx, createReviewSession,
		arg.ID,
		arg.WorkspaceID,
		arg.RepositoryID,
		arg.SnapshotID,
		arg.Title,
		arg.Status,
		arg.ReviewDepth,
		arg.FocusPrompt,
		arg.Preset,
		arg.RuntimeLimitSeconds,
		arg.ContextPolicyJson,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ReviewSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepositoryID,
		&i.SnapshotID,
		&i.Title,
		&i.Status,
		&i.ReviewDepth,
		&i.FocusPrompt,
		&i.Preset,
		&i.RuntimeLimitSeconds,
		&i.ContextPolicyJson,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReviewSession = `-- name: DeleteReviewSession :exec
DELETE FROM review_sessions
WHERE id = ?
`

func (q *Queries) DeleteReviewSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteReviewSession, id)
	return err
}

const getReviewSession = `-- name: GetReviewSession :one
SELECT id, workspace_id, repository_id, snapshot_id, title, status, review_depth, focus_prompt, preset, runtime_limit_seconds, context_policy_json, started_at, completed_at, created_at, updated_at
FROM review_sessions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetReviewSession(ctx context.Context, id string) (ReviewSession, error) {
	row := q.db.QueryRowContext(ctx, getReviewSession, id)
	var i ReviewSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepositoryID,
		&i.SnapshotID,
		&i.Title,
		&i.Status,
		&i.ReviewDepth,
		&i.FocusPrompt,
		&i.Preset,
		&i.RuntimeLimitSeconds,
		&i.ContextPolicyJson,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInterruptedReviewSessions = `-- name: ListInterruptedReviewSessions :many
SELECT id, workspace_id, repository_id, snapshot_id, title, status, review_depth, focus_prompt, preset, runtime_limit_seconds, context_policy_json, started_at, completed_at, created_at, updated_at
FROM review_sessions
WHERE status IN ('queued', 'running', 'canceling')
ORDER BY updated_at ASC, id ASC
`

func (q *Queries) ListInterruptedReviewSessions(ctx context.Context) ([]ReviewSession, error) {
	rows, err := q.db.QueryContext(ctx, listInterruptedReviewSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewSession{}
	for rows.Next() {
		var i ReviewSession
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RepositoryID,
			&i.SnapshotID,
			&i.Title,
			&i.Status,
			&i.ReviewDepth,
			&i.FocusPrompt,
			&i.Preset,
			&i.RuntimeLimitSeconds,
			&i.ContextPolicyJson,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewSessionsByWorkspace = `-- name: ListReviewSessionsByWorkspace :many
SELECT id, workspace_id, repository_id, snapshot_id, title, status, review_depth, focus_prompt, preset, runtime_limit_seconds, context_policy_json, started_at, completed_at, created_at, updated_at
FROM review_sessions
WHERE workspace_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListReviewSessionsByWorkspace(ctx context.Context, workspaceID string) ([]ReviewSession, error) {
	rows, err := q.db.QueryContext(ctx, listReviewSessionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewSession{}
	for rows.Next() {
		var i ReviewSession
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RepositoryID,
			&i.SnapshotID,
			&i.Title,
			&i.Status,
			&i.ReviewDepth,
			&i.FocusPrompt,
			&i.Preset,
			&i.RuntimeLimitSeconds,
			&i.ContextPolicyJson,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewSession = `-- name: UpdateReviewSession :one
UPDATE review_sessions
SET
  title = ?,
  review_depth = ?,
  focus_prompt = ?,
  preset = ?,
  runtime_limit_seconds = ?,
  context_policy_json = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, workspace_id, repository_id, snapshot_id, title, status, review_depth, focus_prompt, preset, runtime_limit_seconds, context_policy_json, started_at, completed_at, created_at, updated_at
`

type UpdateReviewSessionParams struct {
	Title               string         `json:"title"`
	ReviewDepth         string         `json:"review_depth"`
	FocusPrompt         sql.NullString `json:"focus_prompt"`
	Preset              sql.NullString `json:"preset"`
	RuntimeLimitSeconds int64          `json:"runtime_limit_seconds"`
	ContextPolicyJson   string         `json:"context_policy_json"`
	UpdatedAt           string         `json:"updated_at"`
	ID                  string         `json:"id"`
}

func (q *Queries) UpdateReviewSession(ctx context.Context, arg UpdateReviewSessionParams) (ReviewSession, error) {
	row := q.db.QueryRowContext(ctx, updateReviewSession,
		arg.Title,
		arg.ReviewDepth,
		arg.FocusPrompt,
		arg.Preset,
		arg.RuntimeLimitSeconds,
		arg.ContextPolicyJson,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ReviewSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepositoryID,
		&i.SnapshotID,
		&i.Title,
		&i.Status,
		&i.ReviewDepth,
		&i.FocusPrompt,
		&i.Preset,
		&i.RuntimeLimitSeconds,
		&i.ContextPolicyJson,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReviewSessionStatus = `-- name: UpdateReviewSessionStatus :one
UPDATE review_sessions
SET
  status = ?,
  started_at = ?,
  completed_at = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, workspace_id, repository_id, snapshot_id, title, status, review_depth, focus_prompt, preset, runtime_limit_seconds, context_policy_json, started_at, completed_at, created_at, updated_at
`

type UpdateReviewSessionStatusParams struct {
	Status      string         `json:"status"`
	StartedAt   sql.NullString `json:"started_at"`
	CompletedAt sql.NullString `json:"completed_at"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateReviewSessionStatus(ctx context.Context, arg UpdateReviewSessionStatusParams) (ReviewSession, error) {
	row := q.db.QueryRowContext(ctx, updateReviewSessionStatus,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ReviewSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepositoryID,
		&i.SnapshotID,
		&i.Title,
		&i.Status,
		&i.ReviewDepth,
		&i.FocusPrompt,
		&i.Preset,
		&i.RuntimeLimitSeconds,
		&i.ContextPolicyJson,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReviewSessionStatusIfCurrent = `-- name: UpdateReviewSessionStatusIfCurrent :one
UPDATE review_sessions
SET
  status = ?,
  started_at = ?,
  completed_at = ?,
  updated_at = ?
WHERE id = ? AND status = ?
RETURNING id, workspace_id, repository_id, snapshot_id, title, status, review_depth, focus_prompt, preset, runtime_limit_seconds, context_policy_json, started_at, completed_at, created_at, updated_at
`

type UpdateReviewSessionStatusIfCurrentParams struct {
	Status      string         `json:"status"`
	StartedAt   sql.NullString `json:"started_at"`
	CompletedAt sql.NullString `json:"completed_at"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
	Status_2    string         `json:"status_2"`
}

func (q *Queries) UpdateReviewSessionStatusIfCurrent(ctx context.Context, arg UpdateReviewSessionStatusIfCurrentParams) (ReviewSession, error) {
	row := q.db.QueryRowContext(ctx, updateReviewSessionStatusIfCurrent,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.Status_2,
	)
	var i ReviewSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepositoryID,
		&i.SnapshotID,
		&i.Title,
		&i.Status,
		&i.ReviewDepth,
		&i.FocusPrompt,
		&i.Preset,
		&i.RuntimeLimitSeconds,
		&i.ContextPolicyJson,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
