// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbgen

import (
	"context"
)

const deleteEvidenceSearch = `-- name: DeleteEvidenceSearch :exec
DELETE FROM evidence_search
WHERE evidence_item_id = ?
`

func (q *Queries) DeleteEvidenceSearch(ctx context.Context, evidenceItemID string) error {
	_, err := q.db.ExecContext(ctx, deleteEvidenceSearch, evidenceItemID)
	return err
}

const deleteFindingSearch = `-- name: DeleteFindingSearch :exec
DELETE FROM finding_search
WHERE finding_id = ?
`

func (q *Queries) DeleteFindingSearch(ctx context.Context, findingID string) error {
	_, err := q.db.ExecContext(ctx, deleteFindingSearch, findingID)
	return err
}

const insertEvidenceSearch = `-- name: InsertEvidenceSearch :exec
INSERT INTO evidence_search (
  evidence_item_id,
  title,
  summary,
  path
) VALUES (
  ?,
  ?,
  ?,
  ?
)
`

type InsertEvidenceSearchParams struct {
	EvidenceItemID string `json:"evidence_item_id"`
	Title          string `json:"title"`
	Summary        string `json:"summary"`
	Path           string `json:"path"`
}

func (q *Queries) InsertEvidenceSearch(ctx context.Context, arg InsertEvidenceSearchParams) error {
	_, err := q.db.ExecContext(ctx, insertEvidenceSearch,
		arg.EvidenceItemID,
		arg.Title,
		arg.Summary,
		arg.Path,
	)
	return err
}

const insertFindingSearch = `-- name: InsertFindingSearch :exec
INSERT INTO finding_search (
  finding_id,
  claim,
  evidence_summary,
  suggested_fix,
  draft_comment
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type InsertFindingSearchParams struct {
	FindingID       string `json:"finding_id"`
	Claim           string `json:"claim"`
	EvidenceSummary string `json:"evidence_summary"`
	SuggestedFix    string `json:"suggested_fix"`
	DraftComment    string `json:"draft_comment"`
}

func (q *Queries) InsertFindingSearch(ctx context.Context, arg InsertFindingSearchParams) error {
	_, err := q.db.ExecContext(ctx, insertFindingSearch,
		arg.FindingID,
		arg.Claim,
		arg.EvidenceSummary,
		arg.SuggestedFix,
		arg.DraftComment,
	)
	return err
}

const searchEvidence = `-- name: SearchEvidence :many
SELECT evidence_item_id
FROM evidence_search
WHERE title MATCH ?
  OR summary MATCH ?
  OR path MATCH ?
LIMIT ?
`

type SearchEvidenceParams struct {
	Title   string `json:"title"`
	Summary string `json:"summary"`
	Path    string `json:"path"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) SearchEvidence(ctx context.Context, arg SearchEvidenceParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, searchEvidence,
		arg.Title,
		arg.Summary,
		arg.Path,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var evidence_item_id string
		if err := rows.Scan(&evidence_item_id); err != nil {
			return nil, err
		}
		items = append(items, evidence_item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFindings = `-- name: SearchFindings :many
SELECT finding_id
FROM finding_search
WHERE claim MATCH ?
  OR evidence_summary MATCH ?
  OR suggested_fix MATCH ?
  OR draft_comment MATCH ?
LIMIT ?
`

type SearchFindingsParams struct {
	Claim           string `json:"claim"`
	EvidenceSummary string `json:"evidence_summary"`
	SuggestedFix    string `json:"suggested_fix"`
	DraftComment    string `json:"draft_comment"`
	Limit           int64  `json:"limit"`
}

func (q *Queries) SearchFindings(ctx context.Context, arg SearchFindingsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, searchFindings,
		arg.Claim,
		arg.EvidenceSummary,
		arg.SuggestedFix,
		arg.DraftComment,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var finding_id string
		if err := rows.Scan(&finding_id); err != nil {
			return nil, err
		}
		items = append(items, finding_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
