// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createChangedFile = `-- name: CreateChangedFile :one
INSERT INTO changed_files (
  id,
  snapshot_id,
  path,
  old_path,
  status,
  additions,
  deletions,
  is_binary,
  is_generated,
  is_excluded,
  line_ranges_json,
  patch_artifact_id,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, snapshot_id, path, old_path, status, additions, deletions, is_binary, is_generated, is_excluded, line_ranges_json, patch_artifact_id, created_at
`

type CreateChangedFileParams struct {
	ID              string         `json:"id"`
	SnapshotID      string         `json:"snapshot_id"`
	Path            string         `json:"path"`
	OldPath         sql.NullString `json:"old_path"`
	Status          string         `json:"status"`
	Additions       int64          `json:"additions"`
	Deletions       int64          `json:"deletions"`
	IsBinary        int64          `json:"is_binary"`
	IsGenerated     int64          `json:"is_generated"`
	IsExcluded      int64          `json:"is_excluded"`
	LineRangesJson  string         `json:"line_ranges_json"`
	PatchArtifactID sql.NullString `json:"patch_artifact_id"`
	CreatedAt       string         `json:"created_at"`
}

func (q *Queries) CreateChangedFile(ctx context.Context, arg CreateChangedFileParams) (ChangedFile, error) {
	row := q.db.QueryRowContext(ctx, createChangedFile,
		arg.ID,
		arg.SnapshotID,
		arg.Path,
		arg.OldPath,
		arg.Status,
		arg.Additions,
		arg.Deletions,
		arg.IsBinary,
		arg.IsGenerated,
		arg.IsExcluded,
		arg.LineRangesJson,
		arg.PatchArtifactID,
		arg.CreatedAt,
	)
	var i ChangedFile
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Path,
		&i.OldPath,
		&i.Status,
		&i.Additions,
		&i.Deletions,
		&i.IsBinary,
		&i.IsGenerated,
		&i.IsExcluded,
		&i.LineRangesJson,
		&i.PatchArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const createPullRequestSnapshot = `-- name: CreatePullRequestSnapshot :one
INSERT INTO pull_request_snapshots (
  id,
  repository_id,
  source_type,
  provider,
  owner,
  repo,
  pr_number,
  pr_title,
  pr_url,
  base_ref,
  head_ref,
  base_sha,
  head_sha,
  diff_artifact_id,
  metadata_json,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, repository_id, source_type, provider, owner, repo, pr_number, pr_title, pr_url, base_ref, head_ref, base_sha, head_sha, diff_artifact_id, metadata_json, created_at
`

type CreatePullRequestSnapshotParams struct {
	ID             string         `json:"id"`
	RepositoryID   string         `json:"repository_id"`
	SourceType     string         `json:"source_type"`
	Provider       sql.NullString `json:"provider"`
	Owner          sql.NullString `json:"owner"`
	Repo           sql.NullString `json:"repo"`
	PrNumber       sql.NullInt64  `json:"pr_number"`
	PrTitle        sql.NullString `json:"pr_title"`
	PrUrl          sql.NullString `json:"pr_url"`
	BaseRef        sql.NullString `json:"base_ref"`
	HeadRef        sql.NullString `json:"head_ref"`
	BaseSha        sql.NullString `json:"base_sha"`
	HeadSha        sql.NullString `json:"head_sha"`
	DiffArtifactID sql.NullString `json:"diff_artifact_id"`
	MetadataJson   string         `json:"metadata_json"`
	CreatedAt      string         `json:"created_at"`
}

func (q *Queries) CreatePullRequestSnapshot(ctx context.Context, arg CreatePullRequestSnapshotParams) (PullRequestSnapshot, error) {
	row := q.db.QueryRowContext(ctx, createPullRequestSnapshot,
		arg.ID,
		arg.RepositoryID,
		arg.SourceType,
		arg.Provider,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
		arg.PrTitle,
		arg.PrUrl,
		arg.BaseRef,
		arg.HeadRef,
		arg.BaseSha,
		arg.HeadSha,
		arg.DiffArtifactID,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	var i PullRequestSnapshot
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.SourceType,
		&i.Provider,
		&i.Owner,
		&i.Repo,
		&i.PrNumber,
		&i.PrTitle,
		&i.PrUrl,
		&i.BaseRef,
		&i.HeadRef,
		&i.BaseSha,
		&i.HeadSha,
		&i.DiffArtifactID,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const deletePullRequestSnapshot = `-- name: DeletePullRequestSnapshot :exec
DELETE FROM pull_request_snapshots
WHERE id = ?
`

func (q *Queries) DeletePullRequestSnapshot(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePullRequestSnapshot, id)
	return err
}

const getChangedFile = `-- name: GetChangedFile :one
SELECT id, snapshot_id, path, old_path, status, additions, deletions, is_binary, is_generated, is_excluded, line_ranges_json, patch_artifact_id, created_at
FROM changed_files
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetChangedFile(ctx context.Context, id string) (ChangedFile, error) {
	row := q.db.QueryRowContext(ctx, getChangedFile, id)
	var i ChangedFile
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Path,
		&i.OldPath,
		&i.Status,
		&i.Additions,
		&i.Deletions,
		&i.IsBinary,
		&i.IsGenerated,
		&i.IsExcluded,
		&i.LineRangesJson,
		&i.PatchArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const getChangedFileByPath = `-- name: GetChangedFileByPath :one
SELECT id, snapshot_id, path, old_path, status, additions, deletions, is_binary, is_generated, is_excluded, line_ranges_json, patch_artifact_id, created_at
FROM changed_files
WHERE snapshot_id = ? AND path = ?
LIMIT 1
`

type GetChangedFileByPathParams struct {
	SnapshotID string `json:"snapshot_id"`
	Path       string `json:"path"`
}

func (q *Queries) GetChangedFileByPath(ctx context.Context, arg GetChangedFileByPathParams) (ChangedFile, error) {
	row := q.db.QueryRowContext(ctx, getChangedFileByPath, arg.SnapshotID, arg.Path)
	var i ChangedFile
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Path,
		&i.OldPath,
		&i.Status,
		&i.Additions,
		&i.Deletions,
		&i.IsBinary,
		&i.IsGenerated,
		&i.IsExcluded,
		&i.LineRangesJson,
		&i.PatchArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const getPullRequestSnapshot = `-- name: GetPullRequestSnapshot :one
SELECT id, repository_id, source_type, provider, owner, repo, pr_number, pr_title, pr_url, base_ref, head_ref, base_sha, head_sha, diff_artifact_id, metadata_json, created_at
FROM pull_request_snapshots
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPullRequestSnapshot(ctx context.Context, id string) (PullRequestSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getPullRequestSnapshot, id)
	var i PullRequestSnapshot
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.SourceType,
		&i.Provider,
		&i.Owner,
		&i.Repo,
		&i.PrNumber,
		&i.PrTitle,
		&i.PrUrl,
		&i.BaseRef,
		&i.HeadRef,
		&i.BaseSha,
		&i.HeadSha,
		&i.DiffArtifactID,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const listChangedFilesBySnapshot = `-- name: ListChangedFilesBySnapshot :many
SELECT id, snapshot_id, path, old_path, status, additions, deletions, is_binary, is_generated, is_excluded, line_ranges_json, patch_artifact_id, created_at
FROM changed_files
WHERE snapshot_id = ?
ORDER BY path ASC
`

func (q *Queries) ListChangedFilesBySnapshot(ctx context.Context, snapshotID string) ([]ChangedFile, error) {
	rows, err := q.db.QueryContext(ctx, listChangedFilesBySnapshot, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangedFile{}
	for rows.Next() {
		var i ChangedFile
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Path,
			&i.OldPath,
			&i.Status,
			&i.Additions,
			&i.Deletions,
			&i.IsBinary,
			&i.IsGenerated,
			&i.IsExcluded,
			&i.LineRangesJson,
			&i.PatchArtifactID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestSnapshotsByRepository = `-- name: ListPullRequestSnapshotsByRepository :many
SELECT id, repository_id, source_type, provider, owner, repo, pr_number, pr_title, pr_url, base_ref, head_ref, base_sha, head_sha, diff_artifact_id, metadata_json, created_at
FROM pull_request_snapshots
WHERE repository_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListPullRequestSnapshotsByRepository(ctx context.Context, repositoryID string) ([]PullRequestSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listPullRequestSnapshotsByRepository, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestSnapshot{}
	for rows.Next() {
		var i PullRequestSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.SourceType,
			&i.Provider,
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.PrTitle,
			&i.PrUrl,
			&i.BaseRef,
			&i.HeadRef,
			&i.BaseSha,
			&i.HeadSha,
			&i.DiffArtifactID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChangedFileExclusion = `-- name: UpdateChangedFileExclusion :one
UPDATE changed_files
SET is_excluded = ?
WHERE id = ?
RETURNING id, snapshot_id, path, old_path, status, additions, deletions, is_binary, is_generated, is_excluded, line_ranges_json, patch_artifact_id, created_at
`

type UpdateChangedFileExclusionParams struct {
	IsExcluded int64  `json:"is_excluded"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateChangedFileExclusion(ctx context.Context, arg UpdateChangedFileExclusionParams) (ChangedFile, error) {
	row := q.db.QueryRowContext(ctx, updateChangedFileExclusion, arg.IsExcluded, arg.ID)
	var i ChangedFile
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Path,
		&i.OldPath,
		&i.Status,
		&i.Additions,
		&i.Deletions,
		&i.IsBinary,
		&i.IsGenerated,
		&i.IsExcluded,
		&i.LineRangesJson,
		&i.PatchArtifactID,
		&i.CreatedAt,
	)
	return i, err
}
